### ISSUE TITLE
Build fails on master (can not resolve mariaDB4j-db-mac64:jar:10.2.11)

### ISSUE THREAD

**Issue by andersenleo** [vorburger/MariaDB4j#101]
The jitpack builds are failing since the last commit (of OSX binary).

```
[ERROR] Failed to execute goal on project mariaDB4j: Could not resolve dependencies for project ch.vorburger.mariaDB4j:mariaDB4j:jar:2.2.4-SNAPSHOT: Could not find artifact ch.vorburger.mariaDB4j:mariaDB4j-db-mac64:jar:10.2.11 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

Not sure how you handle the binaries, but as far as I can understand they need to be separately deployed to Maven Central in order for MartiaDB4J to build cleanly?

(We're currently depending on the jitpack master-builds while waiting for the next stable version :)).

**Comment by vorburger** [comment]
@andersenleo oups... sorry! Yeah, impact of @jai-deep https://github.com/vorburger/MariaDB4j/pull/97 ...

I've just deployed mariaDB4j-db-mac64 10.2.11 to Maven central, please try again in a few hours?

Intentionally keeping this issue open, for now; please close it when it's OK for you?

**Comment by andersenleo** [comment]
Awesome! Our build-server is happy again :) Thanks for the super-quick fix 👍 

Closing the issue.
