### ISSUE TITLE
trying to stop an already stoped mariadb instance throw nullpointerException

### ISSUE THREAD

**Issue by GararJamal** [vorburger/MariaDB4j#103]
When trying to stop an instance of mariaDB that has not been fully started  (for one reason or another) a null pointer exception is thrown if at this line :+1: 
                              if (mysqldProcess.isAlive()) {...}

is there a way to overcome this other than to go through a native Java code through socket / port ...?

tnx in advance

**Comment by vorburger** [comment]
@GararJamal could you provide the full stack trace of the `NullPointerException` ? 

What is null - the `mysqldProcess` ? In which method - `start()` or `stop()` or `cleanupOnExit()` ?

Perhaps you can come up with a fix yourself and raise a Pull Request... I suspect this will be enough:

```java
    if (mysqldProcess != null && mysqldProcess.isAlive()) {
```

**Comment by GararJamal** [comment]
In fact, I planned to create a pull request proposing this solution but I still wanted to share it with you before doing that

**Comment by vorburger** [comment]
@GararJamal I pull request from you with this solution in `stop()` would be most welcome!
