### ISSUE TITLE
[HELP]  - Which Version Supports configBuilder.setSecurityDisabled(false) ?

### ISSUE THREAD

**Issue by madankn** [vorburger/MariaDB4j#105]
Hi 

[HELP]  - Which Version Supports configBuilder.setSecurityDisabled(false) ?

Madan KN

**Comment by vorburger** [comment]
@madankn configBuilder.setSecurityDisabled(false) will be in 2.2.4 but last on Maven central is 2.2.3.

OK for you to close this issue and subscribe to watch https://github.com/vorburger/MariaDB4j/issues/106 ?

**Comment by madankn** [comment]
@vorburger Thanks for the quick update. It will be great to have 2.2.4 out soon.

Madan KN
