### ISSUE TITLE
Upgrade Mariadb binaries to version >= 10.2.7 in order to support JSON data type

### ISSUE THREAD

**Issue by dargiri** [vorburger/MariaDB4j#107]
Please upgrade binaries to version of mariadb >= 10.2.7 branch in order to support JSON data type which was introduced in 10.2.7: https://mariadb.com/kb/en/library/json-data-type/ .

**Comment by vorburger** [comment]
@dargiri thanks for your interest in this project. FYI this is an open source community effort, not a commercially supported product, so if you need a newer MariaDB version, then please see https://github.com/vorburger/MariaDB4j#mariadb-database-jars-and-version-upgrades how YOU can make a contribution for that!

**Comment by pawel-kaminski-krk** [comment]
hi,
I've read https://github.com/vorburger/MariaDB4j#mariadb-database-jars-and-version-upgrades and I think I understand that. AND I can see that there are
```
ch.vorburger.mariaDB4j | mariaDB4j-db-win32 | 10.2.11  all (4) | 26-Jan-2018 | pom  jar  sources.jar
ch.vorburger.mariaDB4j | mariaDB4j-db-linux64 | 10.2.11  all (4) | 26-Jan-2018 | pom  jar  sources.jar
ch.vorburger.mariaDB4j | mariaDB4j-db-mac64 | 10.2.11  all (4) | 18-Jan-2018 | pom  jar  sources.jar
```
in [search.maven.org](http://search.maven.org/#search%7Cga%7C1%7Cmariadb)

BUT I cannot see any corresponding launcher jar. so am I blind or there is something not published yet :( 

I understand that with those binaries we are almost there. new launcher should have those binary deps included and I should not override versions in my pom's dependencyManagment as I do right now

**Comment by vorburger** [comment]
@pawel-kaminski-krk watch #106 - I'll try to do that (release) ASAP...

**Comment by vorburger** [comment]
@pawel-kaminski-krk so sounds like you are cool with closing this? I have. Comment to re-open if NOK.
