### ISSUE TITLE
Configuration dont work in windows 10

### ISSUE THREAD

**Issue by FactorySolution** [vorburger/MariaDB4j#108]
I try configure the application, but always return this error

com.sun.jdi.ClassNotLoadedException: Type has not been loaded occurred while retrieving component type of array.

this method dont find jar in application 

 public static int extractFromClasspathToFile(String packagePath, File toDir) throws IOException 

My configuration: 
    	DBConfigurationBuilder configBuilder = DBConfigurationBuilder.newBuilder();
        configBuilder.setPort(3306);
        configBuilder.setDataDir("target/mariaDB");
        configBuilder.setBaseDir("target/mariaDB");
        DB database = DB.newEmbeddedDB(configBuilder.build());
        database.start();

thanks

**Comment by vorburger** [comment]
#229 says that Windows works ... closing this. Try again with an (upcoming) new release including #229.

> com.sun.jdi.ClassNotLoadedException: Type has not been loaded occurred while retrieving component type of array.

I've never seen this error before, and only 1 user reported it; suspect it is some local problem.
