### ISSUE TITLE
Built-in ROW_NUMBER() functions does not exist

### ISSUE THREAD

**Issue by mparadadodaxcom** [vorburger/MariaDB4j#109]
I am  trying to cover some update statement by unit test on mariadb4j, but I got error that ROW_NUMBER() does not exist inside mariadb4j instance, is there any workaround for that case?

**Comment by vorburger** [comment]
@mparadadodaxcom it's probably a MariaDB version issue; I've no idea what ROW_NUMBER() is but it's perhaps only available in newer version of MariaDB than the one packaged with MariaDB4j? If you have a closer look at the README, you'll see how you can either yourself package newer version or even contribute them to this project.

**Comment by mparadadodaxcom** [comment]
I was writing about https://mariadb.com/kb/en/library/row_number, I will check compability with my production mariadb instance.

**Comment by xisvaldo** [comment]
Any news about it? Or workaround?

**Comment by vorburger** [comment]
Again, I've no idea what MariaDB version `ROW_NUMBER()` was introduced in, but FYI I've just merged #235 for #230 where @srbala (@jtmuhone) contributed MariaDB 10.3.13 binaries (before we had 10.2.11), perhaps that is recent enough? If you need 10.4 for `ROW_NUMBER()`, then a PR contributing (similar to #235) is welcome...
