### ISSUE TITLE
Using MariaDb4j with Atlassian pipeline

### ISSUE THREAD

**Issue by 3lix** [vorburger/MariaDB4j#110]
We're attempting to integrate ci/cd with our workflow. We landed on this project in order to unit test our database access calls. 
We integrated the unit tests with MariaDb4j. The tests run well locally but are failing in Atlassian's pipeline with the following error

> An error occurred while starting the database
> ch.vorburger.exec.ManagedProcessException: An error occurred while starting the database
> Caused by: ch.vorburger.exec.ManagedProcessException: 
> Asked to wait for "mysqld: ready for connections." from Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3333, --port=3333, --socket=/tmp/MariaDB4j.3333.sock] (in working directory /tmp/MariaDB4j/base), but it already exited! (without that message in console), last 100 lines of console:
> 2018-03-18  4:36:56 139657118295552 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.1.13-MariaDB) starting as process 3675 ...
> 2018-03-18  4:36:56 139657118295552 [ERROR] Fatal error: Please consult the Knowledge Base to find out how to run mysqld as root!

Would you have any insights to this problem?

**Comment by vorburger** [comment]
> Would you have any insights to this problem?

unfortunately not. Perhaps on the Atlassian pipeline there are some limitation as to what external processes you can and cannot start? The message just seems to say that the start of mysqld immediately failed. You should probably check more in the MariaDB community itself or some Atlassian pipeline forum or something.

If you find the solution, will you update here to help others? I'll close this issue in 1 months after last comment.

**Comment by senki1988** [comment]
It might be due to the fact that Atlassian pipeline runs docker containers in **non privileged** mode.

**Comment by yiftizur** [comment]
I resolved it in our pipelines (although it was Gitlab, but also docker) by adding the `--user=root` arg to the db config:
`DBConfiguration config = DBConfigurationBuilder.newBuilder()
            .addArg("--user=root")
            .build();`

**Comment by vorburger** [comment]
@yiftizur can this issue be closed, or is there any follow up action here? Wanna contribute anything re. this? :smile:

**Comment by yiftizur** [comment]
@vorburger For me this resolved it :) however i don't know if @3lix can confirm...
I'll think about how we can solve this programmatically :smiley:

**Comment by vorburger** [comment]
@3lix please comment if you need this issue to be re-opened (and, ideally, contribute a solution!).

**Comment by pll** [comment]
I'm currently running into this exact problem.  The issue at hand is that MariaDB seems to getting executed "as root" when run in a docker container.  I've tried editing the application.yml file, and even the above recommendation of using `addArg()` to insert `--user=root` into the command line that starts MariaDB. Neither work.

I've even gone so far as to build an entirely new docker container with a non-root user and for some reason MariaDB still fails with:
```
20:19:56.581 [DEBUG] [TestEventLogger]     Caused by: ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld: ready for connections." from Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M,
--basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3307, --port=3307, --socket=/tmp/MariaDB4j.3307.sock] (in working directory /tmp/MariaDB4j/base), but it already exited! (without that message in console), last 100 lines of console:
20:19:56.582 [DEBUG] [TestEventLogger]     2022-01-13 20:19:52 139953619939456 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.2.11-MariaDB) starting as process 1789 ...
20:19:56.583 [DEBUG] [TestEventLogger]     /tmp/MariaDB4j/base/bin/mysqld: Please consult the Knowledge Base to find out how to run mysqld as root!
20:19:56.583 [DEBUG] [TestEventLogger]     2022-01-13 20:19:52 139953619939456 [ERROR] Aborting
```

I'm kind of at a loss here on how to configure MariaDB to run from within a Docker container as an embedded DB for my team's Java tests.

Any help/pointers would be greatly appreciated.

Thanks!

**Comment by fedigiorgio** [comment]
> I'm currently running into this exact problem. The issue at hand is that MariaDB seems to getting executed "as root" when run in a docker container. I've tried editing the application.yml file, and even the above recommendation of using `addArg()` to insert `--user=root` into the command line that starts MariaDB. Neither work.
> 
> I've even gone so far as to build an entirely new docker container with a non-root user and for some reason MariaDB still fails with:
> 
> ```
> 20:19:56.581 [DEBUG] [TestEventLogger]     Caused by: ch.vorburger.exec.ManagedProcessException: Asked to wait for "mysqld: ready for connections." from Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M,
> --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3307, --port=3307, --socket=/tmp/MariaDB4j.3307.sock] (in working directory /tmp/MariaDB4j/base), but it already exited! (without that message in console), last 100 lines of console:
> 20:19:56.582 [DEBUG] [TestEventLogger]     2022-01-13 20:19:52 139953619939456 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.2.11-MariaDB) starting as process 1789 ...
> 20:19:56.583 [DEBUG] [TestEventLogger]     /tmp/MariaDB4j/base/bin/mysqld: Please consult the Knowledge Base to find out how to run mysqld as root!
> 20:19:56.583 [DEBUG] [TestEventLogger]     2022-01-13 20:19:52 139953619939456 [ERROR] Aborting
> ```
> 
> I'm kind of at a loss here on how to configure MariaDB to run from within a Docker container as an embedded DB for my team's Java tests.
> 
> Any help/pointers would be greatly appreciated.
> 
> Thanks!

Try to add this in Dockerfile

`RUN apt update
RUN apt-get --assume-yes install libncurses5`

In addition to 
`"--user=root"`
in DBConfigurationBuilder.

**Comment by pll** [comment]
Hi @fedigiorgio,

Thanks for the reply.  The container is RH based, but I do exec `yum update` when I build the container. And libncurses6 is already installed, though I'm not entirely clear on why installing libncurses would then allow MariaDB to run in the container.  Could explain the connection between this issue and libncurses being the solution ?

Thanks!
--
Paul
