### ISSUE TITLE
Enable multiple srcripts to be sourced like flyway:migrate

### ISSUE THREAD

**Issue by usmanakram232** [vorburger/MariaDB4j#112]
Enable flyway style migration scripts to be sourced.

I propose, we add a new method which take the path to directory containing migration scripts and sources them in order.

``` java
  public void migrate(String directory, String suffix)
```

**Comment by usmanakram232** [comment]
As, discussed in PR #113 instead of trying to replicate flyway:migrate. We can have a `sourceAll` method with loads all the script in given directory.

**Comment by vorburger** [comment]
@usmanakram232 sounds good to me (and @duttonw seems to like this as well).

More FTR in #113 this is going to be named `sourceAll()` not `migrate()` - that makes sense.

Once #113 is merged, can this issue be closed, or will there be anything else to do in this issue?

**Comment by usmanakram232** [comment]
@vorburger yes, we can close this issue upon merge,

**Comment by vorburger** [comment]
@usmanakram232 hope you don't mind if I close this issue, we have the active #113 PR to track it now.
