### ISSUE TITLE
Dropping a database

### ISSUE THREAD

**Issue by jeanpic** [vorburger/MariaDB4j#136]
I'm trying to change the database with a different sql script but I can't seem to succeed.

I tried 
``db.source("oldDB.sql","root","","databasename");``
``db.stop();``
  `db.start();`
  `db.createDB("p64pacd");`
  `db.source("newDB.sql","root","","databasename");`

Hoping that stopping the DB will drop the database, but it doesn't seem so. Modifying the database with request works, but I'd rather use another sql script. How can I drop the database ?

**Comment by vorburger** [comment]
@jeanpic re. _"Hoping that stopping the DB will drop the database",_ that's not really how it works...   you would have to yourself wipe the `DBConfiguration.getDataDir()` directory. Hope this helps, and OK to close this issue?

**Comment by jeanpic** [comment]
I see, thank you !

**Comment by tcve** [comment]
I know this is closed, but I'm also having an issue dropping a database! I want to have full test isolation by wiping out the database between each test, so to do that I tried dropping the database like so in the JUnit `@After`:
`db.getDB().run("DROP DATABASE databasename");`
`db.getDB().createDB("databasename");`
`db.getDB().source("schema.sql");`

However, the process hangs on that first line that runs the DROP command. In particular, it hangs on `ManagedProcess.waitForExit()`.

Am I using this wrong? Is there a better way to achieve test isolation with MariaDB4j?

**Comment by vorburger** [comment]
@tcve can I suggest that you open a new issue instead of commenting on an old closed one, and link to this?

> the process hangs on that first line that runs the DROP command. In particular, it hangs on ManagedProcess.waitForExit(). 

Have a good close look yourself at the log it prints to see why it hangs? If you cannot, post the full log in the new issue.

> Is there a better way to achieve test isolation with MariaDB4j?

You guess you could try to yourself wipe the DBConfiguration.getDataDir() directory, and re-start `DB`.
