### ISSUE TITLE
How resolve space in dataDir or baseDir [RESOLVED]

### ISSUE THREAD

**Issue by appscharles** [vorburger/MariaDB4j#137]
For windows: replace all white spaces to ~

**Comment by ZeroTau** [comment]
This does not work for me. If I set the baseDir to `C:\t~e~s~t\` then MariaDB is just installed into the directory with tildes if I use `C:\TEST~1\` then the install fails, but sis started in the correct location.

**Comment by ZeroTau** [comment]
The proposed fix did not work for me.

**Comment by vorburger** [comment]
I don't use Windows myself - could any windows users help here? (Or close this issue.)

**Comment by vorburger** [comment]
#229 probably fixed this issue - can you guys who hit it here verify that?
