### ISSUE TITLE
Distribution might not be eligible for Apache v2 Licensing

### ISSUE THREAD

**Issue by johnament** [vorburger/MariaDB4j#14]
Please look at section 4 of the Apache v2 License, at [apache.org].  I believe that this binary is not eligible for the Apache v2 license as it redistributes incompatibly licenses binaries, specifically what appears to be a mysql binary.  I believe you must include a NOTICE file explaining any of these 3p dependencies with incompatible licenses.

[apache.org]: http://www.apache.org/licenses/LICENSE-2.0.html#redistribution

**Comment by lpearson05** [comment]
I noticed this implementation (https://github.com/wix/wix-embedded-mysql/commit/41583eb74c9056c1841494f65a86f7a70602924c) switched to BSD license. Don't exactly know how they compare, though.

**Comment by kedgecomb** [comment]
Which binary is the "incompatibly licensed binary"? (just looking for a way around this)
The mysql.exe and mysqld.exe objects are mariadb binaries, right?

**Comment by vorburger** [comment]
I'm considering this done with https://github.com/vorburger/MariaDB4j/commit/e6fa766ccf54ac5052edfd5b53e545e36131db2a and https://github.com/vorburger/MariaDB4j/commit/243471891ab6bdb61fea1020c85d6ecec23ec300.

Please re-open if you have further more specific input (ideally with a Pull Request leading the way by example...).
