### ISSUE TITLE
Error with JUnit Test and MariaDB4j

### ISSUE THREAD

**Issue by fabien91** [vorburger/MariaDB4j#140]
Hi,

I have an problem with MariaDB4j, it can't finish all test, i have this error :

https://pastebin.com/pyU2fAb7

Could you help me please ?

Fabien

**Comment by fabien91** [comment]
I found solution after 3min....

I've forgot to stop database with @After on junit

**Comment by vorburger** [comment]
> I've forgot to stop database with @after on junit

@fabien91 then you'll like @yiftizur's upcoming JUnit `@Rule` in https://github.com/vorburger/MariaDB4j/pull/139 .. 

with that, you won't be able to forget anymore! :smile:
