### ISSUE TITLE
support for connection.createArrayOf

### ISSUE THREAD

**Issue by OfekCyberX** [vorburger/MariaDB4j#167]
I am using this library for mocking mysql, and its great :)
Tried to use `createArrayOf` and got an exception:
```
Caused by: java.sql.SQLFeatureNotSupportedException: Not yet supported
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getFeatureNotSupportedException(ExceptionMapper.java:215)
	at org.mariadb.jdbc.MariaDbConnection.createArrayOf(MariaDbConnection.java:1450)
```

Is this a jdbc version issue? are there plans to support this?
I am using version 2.3.0

```
<dependency>
      <groupId>ch.vorburger.mariaDB4j</groupId>
      <artifactId>mariaDB4j</artifactId>
       <version>2.3.0</version>
 </dependency>
```

**Comment by vorburger** [comment]
@OfekCyberX sounds like you're good. If you leave a comment what the problem was and how you've solved it, it could help others in the future who can find this issue by searching for that error.

**Comment by OfekCyberX** [comment]
Yeah, apparently there is not support for ``` connection.createArrayOf ``` in the java jdbc driver, so its not an issue of the mock library but of the java driver.
If there a is a jdbc driver for java that does support this, it'll be great! I couldn't find an example that uses createArrayOf with the java driver.

**Comment by vorburger** [comment]
Right so this isn't really about MariaDB4j (this project) but the [MariaDB Connector](https://downloads.mariadb.org/connector-java/) (mariadb-java-client). Have you considered filing an issue about this on https://jira.mariadb.org on the CONJ project? You could also verify which version of mariadb-java-client we use here and upgrade that to the latest (if any), but I doubt that will help. FTR these seem to useful related references:

* https://stackoverflow.com/questions/22066316/error-with-mysql-jdbc-driver-for-method-createarrayof
* http://javadox.com/org.mariadb.jdbc/mariadb-java-client/1.1.7/org/mariadb/jdbc/MySQLConnection.html#createArrayOf(java.lang.String,%20java.lang.Object[])
