### ISSUE TITLE
Any specific need for the --skip-grant-tables?

### ISSUE THREAD

**Issue by kaismh** [vorburger/MariaDB4j#17]
I would like to secure the DB, does MariaDB4j needs the --skip-grant-tables argument? Can it be removed safely?

**Comment by vorburger** [comment]
@kaismh how about we add some method to REMOVE parameters which MariaDB4j adds by default? A bit similar to https://github.com/vorburger/MariaDB4j/pull/23, but sort of the opposite of it... thoughts? Any PRs welcome, BTW.. ;-)

**Comment by vorburger** [comment]
@kaismh are you alive? I finally have time to pick up MariaDB4j maintenance, and if you would like to contribute a PR with what you had in mind above, I'd certainly look at and merge it ..

**Comment by azell** [comment]
I would also find this useful.  Let me taker a look at the code this weekend.

**Comment by vorburger** [comment]
Closing as this is DONE via https://github.com/vorburger/MariaDB4j/pull/83 - big TX to all who contributed in the discussion here, and to @marcelvanderperk for the code!
