### ISSUE TITLE
Bringing wrong mariadb version on windows 10?

### ISSUE THREAD

**Issue by JimiJones** [vorburger/MariaDB4j#179]
When I build my application using embedded mariadb database for test, I got this: 
mysqld.exe (mysqld 10.2.11-MariaDB) starting as process ...
ERROR: Cannot write to mysqld's stdin
FATAL ERROR: database creation failed

I think it's because it bring a wrong mariadb version. Actually I got the same when I go to the mysql_install_db.exe directory and I run it.

I use MariaDB4j 2.3.0 and it bring mariadb 10.2.11.

**Comment by vorburger** [comment]
I don't use Windows myself - could any windows users help here? (Or close this issue.)

**Comment by vorburger** [comment]
#229 probably fixed this issue - can you verify that?
