### ISSUE TITLE
MariaDB4J integration with Spring Boot 2.0.4 

### ISSUE THREAD

**Issue by sauravGit** [vorburger/MariaDB4j#180]
Hi,
I am able to successfully use with Spring Boot 2.0.4 release with flywayDB migration script. I think the MariaDB4J does not support JSON column type.

**Comment by vorburger** [comment]
>  I think the MariaDB4J does not support JSON column type.

@sauravGit this is probably because of the version of MariaDB you use with MariaDB4j ?

see also related older issues #49 and #107 ...

**Comment by vorburger** [comment]
@sauravGit the mariaDB4j-springboot which is about to be released with 2.4.0 (watch #165) provides nice MariaDB4J integration with Spring Boot.  The JSON column type issue may need to if contribute https://github.com/vorburger/MariaDB4j#mariadb-database-jars-and-version-upgrades a new MariaDB binary to this project. I'm therefore closing this issue, hope that's OK.
