### ISSUE TITLE
increase max_connections variable

### ISSUE THREAD

**Issue by jonbrmasson** [vorburger/MariaDB4j#193]
Is there a possibility to increase the `max_connections` variable to say 151, currently my installation has 100, and it's always maxing out with the following message: `too many connections`

**Comment by thesquaregroot** [comment]
You can set properties like this using the DBConfigurationBuilder.  For example:

`config.addArg("--max-connections=151");`

**Comment by vorburger** [comment]
@jonbrmasson you'll probably need the hopefully about to be released 2.4.0 (watch #165) with @thesquaregroot's #133. Therefore closing this, please comment to re-open if NOK for you.
