### ISSUE TITLE
Version 2.3.0 ManagedProcessException

### ISSUE THREAD

**Issue by radubalanpro** [vorburger/MariaDB4j#197]
error: cannot access ManagedProcessException
        db = DB.newEmbeddedDB(config.build());
  class file for ch.vorburger.exec.ManagedProcessException not found
1 error

**Comment by vorburger** [comment]
Hello, thank you for your interest in this project. Unfortunately this is
too little information for a bug report.. The
ch.vorburger.exec.ManagedProcessException class is, of course, there...
note the passing tests. I suspect that you may have some class loading
issues?

>

**Comment by vorburger** [comment]
> The only thing i did was to switch from working 2.2.3 libraties to 2.3.0.
> I suppose that code is backward compatible. In 2.3.0 xore the class is not
> there ... or i didn't saw it
>

FYI the exec related code was moved out from MariaDB4j into a separate new
project & JAR.

With Maven or Gradle that gets automatically pulled as a transitive
dependency, but it sounds like you manage your dependencies manually - then
you have to add that new ch.vorburger.exec JAR...

Ok to close this issue?

>
