### ISSUE TITLE
Could not find artifact ch.vorburger.mariaDB4j:mariaDB4j-springboot:jar:2.3.1-SNAPSHOT

### ISSUE THREAD

**Issue by firatkucuk** [vorburger/MariaDB4j#198]
seems mariaDB4j-springboot jar is not in the main maven repository.

**Comment by vorburger** [comment]
On Thu, 10 Jan 2019, 07:47 Fırat KÜÇÜK <notifications@github.com wrote:

> seems mariaDB4j-springboot jar is not in the main maven repository.
>
mariaDB4j-springboot should be, but 2.3.1-SNAPSHOT will not, that's is
normal, SNAPSHOT versions are never on Maven central, only releases.

Can you elaborate on your problem?

**Comment by firatkucuk** [comment]
https://search.maven.org/search?q=g:ch.vorburger.mariaDB4j

those are the all artifacts. Seems no springboot artifact.

**Comment by vorburger** [comment]
@firatkucuk oh sorry, just realized this will need #165 .. I'll try to get to this some time this or next week.

**Comment by vorburger** [comment]
@firatkucuk I'm hoping to release 2.4.0 (#165) ASAP - I'll close this issue, shout (comment) if NOK.
