### ISSUE TITLE
Provide "isRunning" method

### ISSUE THREAD

**Issue by scrobbleme** [vorburger/MariaDB4j#20]
We try to use this package for running unit tests against a "real" local MySQL database. This also works very good so far.  

The only problem is, that it doesn't seem to be able to start and stop the database sequentially.

* We have an abstract base test, which starts and stops the database
* All tests inherit from this.
* Now running multiple tests results in all subsequent test failing as the port is still used.   
* We are using TestNG

It would be nice to have a method, like "isRunning" to check, if the database is still running. Another option would be to have an additonal stopAndWait

**Comment by scrobbleme** [comment]
Okay, while preparing a sample project I found out, that it is more a typical "forget to release resources" problem and though there was still a JDBC connection open.

Can be closed ;)

The example project: https://github.com/scrobbleme/embedded-mariadb-test

**Comment by vorburger** [comment]
Hallo - OK, closing - these are my favourite kind of issues.. ;-) Had a look at your example, cool! Similar to https://github.com/vorburger/MariaDB4j/blob/master/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java (just in case you hadn't seen that). Thanks for your interest, and BTW - Pull Requests for MariaDB4j always welcome! ;-)

**Comment by scrobbleme** [comment]
Thanks, haven't seen your example. Might have saved some time ;)
