### ISSUE TITLE
Add support for MariaDB 10.3.2+

### ISSUE THREAD

**Issue by qinghui-xu** [vorburger/MariaDB4j#202]
The newer versions (>=10.3.2) of MariaDB have the column compression feature (independent of the storage engine). It is interesting to have this version to be able to run some test with the compression feature.

**Comment by vorburger** [comment]
@qinghui-xu thanks for your interest in this project. FYI this is an open source community effort, not a commercially supported product, so if you need a newer MariaDB version, then please see https://github.com/vorburger/MariaDB4j#mariadb-database-jars-and-version-upgrades how YOU can make a contribution for that!

**Comment by qinghui-xu** [comment]
Hi, @vorburger.
Yes, it makes sense. I'll try to do that when I got some time.

**Comment by vorburger** [comment]
#229 did this.
