### ISSUE TITLE
Plugin mariaDB4j-maven-plugin in Maven central

### ISSUE THREAD

**Issue by JimiJones** [vorburger/MariaDB4j#205]
Is mariaDB4j-maven-plugin deployed in maven central? I can't find it using:
```
<dependency>
    <groupId>ch.vorburger.mariaDB4j</groupId>
    <artifactId>mariaDB4j</artifactId>
    <version>2.3.0</version>
</dependency>
```

and then:

```
<plugin>
    <groupId>ch.vorburger.mariaDB4j</groupId>
    <artifactId>mariaDB4j-maven-plugin</artifactId>
    <version>2.3.0</version>
    <executions>
        <execution>
        ...
    </executions>
</plugin>
```

**Comment by vorburger** [comment]
The 2.3.0 version is, just see here https://search.maven.org/search?q=ch.vorburger.mariadb4j but the mariaDB4j-maven-plugin is 2.4.0 only and that's TBD, watch https://github.com/vorburger/MariaDB4j/issues/165 ... hopefully soon; in the mean time, you can, of course, locally build from source. 

OK for you to close this issue?

**Comment by JimiJones** [comment]
Oh ok I was thinking it was on 2.3.0 reading the readme.
Yes, you can close it.

**Comment by vorburger** [comment]
>  Yes, you can close it.

feel free to close issues you opened on GitHub yourself any time, nobody will mind.
