### ISSUE TITLE
MariaDB4j in Maven central

### ISSUE THREAD

**Issue by nicmon** [vorburger/MariaDB4j#21]
Is it possible to deploy MariaDB4j in Maven Central to avoid build the Project everytime we want to use it? Thank you.

**Comment by vorburger** [comment]
Hi @nicmon - cool that you find MariaDB4j useful and use it. I'll see how I can get it into Maven Central some time (probably using http://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/). In the mean time, perhaps the README update https://github.com/vorburger/MariaDB4j/commit/976cd15955c415a8c775deadd09786b7e99fcbdc#diff-04c6e90faac2675aa89e2176d2eec7d8 is useful to you?

**Comment by metawave** [comment]
+1

**Comment by krm1312** [comment]
Would be nice if it was in maven central.

**Comment by alexpanov** [comment]
Please do release it to Central.

**Comment by jinahya** [comment]
I'm writing a jdbc-related library. And I made a test case for PostgreSQL with [postgresql-embedded](https://github.com/yandex-qatools/postgresql-embedded) along with H2, Derby, and HSQL.
It will be great if I can add another test case for MariaDB.

**Comment by kedgecomb** [comment]
Please do release it to Central.

**Comment by lc-nyovchev** [comment]
+1

**Comment by tbenedetti-lendico** [comment]
+1

**Comment by fleger** [comment]
+1

**Comment by antoinecarton** [comment]
+1

**Comment by vorburger** [comment]
Hello everyone thanks for all of your interest in MariaDB4j! 

I'm hoping to get to this one in the next 1-2 weeks or so; I've just been busy with other prios.

**Comment by vorburger** [comment]
All please note that you can easily get the latest released versions from Bintray, and the latest SNAPSHOT from jitpack; I've just documented this on https://github.com/vorburger/MariaDB4j#where-from ... 

I'm assuming that you STILL want Maven Central anyway? OK.. I'll try, watch https://issues.sonatype.org/browse/OSSRH-22232 

BTW: Who are you all, and in what projects / applications do you use MariaDB4j? FLOSS, or .com? Please feel free to send a PR linking to your-own-cool-project-using-MariaDB4j for the [Who's using it?](https://github.com/vorburger/MariaDB4j#whos-using-it) README section.

**Comment by chrisbloe** [comment]
Hi @vorburger

Thank you very much for your awesome work on this project :)

I work for [Costcutter](https://en.wikipedia.org/wiki/Costcutter) in the UK and we use MariaDB4j for our integration testing.

**Comment by fleger** [comment]
I work for [Enovea](http://www.enovea.net/en) where we use MariaDB4j for integration testing on our [Financial Reconciliation](http://crystalrec.com/index.php/en/) product.

**Comment by lc-nyovchev** [comment]
Hey, great job on MariaDB4j!

I work for [Relay42](http://relay42.com/) in the Netherlands where we use MariabDB4j for unit and integration testing.

**Comment by ollemuhr** [comment]
+1

**Comment by laurent-dol** [comment]
+1

**Comment by vorburger** [comment]
Hello everyone & @CedricGatay : Thanks for your patience, and continued support for the project from all of you.

I think I'm very close to having MariaDB4j v2.2.1 fully [available on Maven central!](http://search.maven.org/#search%7Cga%7C1%7Cmariadb4j). Just waiting for clarification to my latest question in https://issues.sonatype.org/browse/OSSRH-22232. Or may just needs an hour or whatever to sync and then it's fine by itself by the time you read this.. Once that's clarified, perhaps some of you would then like to test it, and confirm this is OK to close for good?

Also, see https://github.com/vorburger/MariaDB4j/blob/master/USERS.md with some of you all - hope OK. If you're reading this, and are using MariaDB4j but don't appear in the new USERS (or CONTRIBUTORS) then please do feel free to raise a PR to add yourselves! ;-)

PS just FYI: https://issues.sonatype.org/browse/OSSRH-23885

**Comment by CedricGatay** [comment]
Looks good to me, keep up the good work ! (sync on central is not always fast, especially with large jars)

**Comment by hanklank** [comment]
Worked fine for me from mavencentral - thanks - tested linux .10.1.13 (the mariaDB4j-db-linux64-artifact for version 10.1.8 didn't work, but that seems to be missing some binaries/src folder in master branch which explains it).

**Comment by vorburger** [comment]
Cool guys, thanks for your feedback. With 22118a3875d5a65055bdee77f065ef2b8ae87368, considering this one closed then!

**Comment by navdeepniku** [comment]
Any plans to periodically release new versions? The last release 2.4.0 was done on 12 Feb 2019
