### ISSUE TITLE
Anyone interested in becoming an additional issue answerer and code reviewers with promised committer privilege to this project?

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#213]
If anyone reading this is interested in helping me maintain this project, please speak up in this issue...

... my idea would be that if you (a) [have made some contribution/s yourself](https://github.com/vorburger/MariaDB4j/graphs/contributors), even small is totally cool, and/or (b) [comment to help with open issues](https://github.com/vorburger/MariaDB4j/issues) (start by cleaning up existing open issues?) and (c) and/or help [review code in open PRs](https://github.com/vorburger/MariaDB4j/pulls) going forward, then I would be interested in adding you as an additional committer.

Some background in re. how I've handled this in another project:

* https://github.com/m2e-code-quality/m2e-code-quality/issues/124
* http://blog2.vorburger.ch/2019/02/about-you-and-that-open-source-thing.html
* https://github.com/m2e-code-quality/m2e-code-quality/issues/208

Looking forward to hearing :small_airplane: from the MariaDB4j community!

**Comment by srbala** [comment]
@vorburger I am interested

**Comment by srbala** [comment]
@vorburger would you consider moving this project to it's own organisation? Name `MariaDB4j`seems avilable https://github.com/mariadb4j. 

You can use https://github.com/organizations/new to setup. You can transfer repository after setup.

**Comment by vorburger** [comment]
> @vorburger would you consider moving this project

Let's take that over into new issue #238!

**Comment by vorburger** [comment]
So, according to the helpful buttons at the very top of this page, MariaDB4j today is Used By 152 projects, Watched By 23 users, starred by 408, forked 95, but only 1 person spoke up here willing to help maintain it?! :smiling_imp: 

I'd really welcome more people stepping up and e.g. review open PRs, and clean up open Issues...

**Comment by vorburger** [comment]
@glittle1972 would you be interested in being invited to become a committer on this project?

**Comment by glittle1972** [comment]
@vorburger I'm on holiday at the moment. Can I think about it as I'm aware this if my first open source contributions and there's a few bits of hooks and automations in GitHub that I don't know about yet?

Cheers.

**Comment by vorburger** [comment]
@glittle1972 don't worry about the few bits of hooks and automations in GitHub, I'll handle those; I'm more looking for additional people willing to maintain the code, like help review new PRs, merge then when fine, reply on new issues, help clean up and close old issues, etc.

**Comment by StruckCroissant** [comment]
I'd be willing to help out a bit - although my experience working with open source projects & PR/Issue/Review maintenance is almost nil - except for the project that I've been working on lately by myself.

**Comment by vorburger** [comment]
@StruckCroissant thanks! I would love to see some PRs from you!

@mrdziuban could this interest you?
