### ISSUE TITLE
"Address already in use" when trying to start DB

### ISSUE THREAD

**Issue by OfekCyberX** [vorburger/MariaDB4j#214]
Hello,
So I have been using mariadb4j for my junits, and its really great! thanks for that!
So what I have is multiple test classes which all use this mocked mysql db to test different things.
In my pom.xml, I make sure all the tests run synchronously so only one test uses the mock every time.

It works well most of them time - but I had a failure saying:
```
16:48:05.782 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld: 2019-02-11 16:48:05 140320527034240 [ERROR] Can't start server: Bind on TCP/IP port. Got error: 98: Address already in use
16:48:05.797 [Exec Stream Pumper] ERROR ch.vorburger.exec.ManagedProcess - mysqld: 2019-02-11 16:48:05 140320527034240 [ERROR] Do you already have another mysqld server running on port: 50108 ?
```
What I have is a class extending `ExternalResource` which has **before** and **after**.
This those **before** and **after** methods should run **per test method** in each class.

```
private DBConfigurationBuilder builder = DBConfigurationBuilder.newBuilder()
            .setPort(0).addArg("--character-set-server=latin1");
private DB db;

@Override
    protected void before() throws Throwable {
        db = DB.newEmbeddedDB(builder.build());
        int count = 0;
        boolean success = false;
        while (count < ATTEMPTS && !success) {
            try {
                db.start();
                success = true;
            } catch (Exception e) {
                count++;
                System.out.println("Attempt " + count + " out of " + ATTEMPTS);
                if (count == ATTEMPTS) {
                    throw e;
                }
            }
        }

        db.source(schemaPath);
  }



@Override
    protected void after() {
        try {
            db.stop();
        } catch (ManagedProcessException e) {
            e.printStackTrace();
        }
    }
```

I figured the **after** method will make sure to stop the DB before the next test starts, but from the error What I understand is that a previous mock instance didn't stop and there is a collision in the ports used for the mock (I use port 0 to take an available port).

I there anything I can do to solve this? I seems to work most of the time, but I get failures sometimes.
Using version 2.3.0.

Thanks!

**Comment by vorburger** [comment]
> What I have is a class extending `ExternalResource` 

@OfekCyberX did you see that the [just released MariaDB4j v2.4.0](https://github.com/vorburger/MariaDB4j/blob/master/CHANGELOG.md) includes a cool new [MariaDB4jRule](https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/junit/MariaDB4jRule.java) JUnit rule which @yiftizur contributed? 

You can probably just use that? 

OK to close this issue?

**Comment by yiftizur** [comment]
@OfekCyberX maybe the MariaDB4jRule after() method will stop test run if stopping the DB isntance fails... I does not solve the issue of why a DB instance may fail to stop, but at least you will not try to start a new one while there is one running...

**Comment by OfekCyberX** [comment]
@vorburger thanks for your answer.
This issue still happens to me when using `MariaDB4jRule`.

Error is 
```
2019-02-17  9:30:53 139940564486016 [Note] Server socket created on IP: '::'.
2019-02-17  9:30:53 139940564486016 [ERROR] Can't start server: Bind on TCP/IP port. Got error: 98: Address already in use
2019-02-17  9:30:53 139940564486016 [ERROR] Do you already have another mysqld server running on port: 47838 ?
```

The way I use this class is, I have another class extending `MariaDB4jRule` which has a static variable for the `DBConfigurationBuilder` with port 0 (to detect a free port on the File System).

```
public class MysqlMockResource extends MariaDB4jRule {

    private static DBConfigurationBuilder builder = DBConfigurationBuilder.newBuilder().setPort(0);
```

I use this class with `@Rule` annotation in my test classes.
Now, the class had failed test, for example, had 13 tests in it, so what happens is that the port is set **only once** per class, because its the configuration is static.

**But** - for each test method the `before` and `After` methods are called, so the db starts and stop every test, and the port stays the same for all the test methods in the class.

Maybe this is what causing the issue? What is the best practice to using `MariaDB4jRule` , because I keep getting this error of "Address already in use".

**Comment by vorburger** [comment]
>  I have another class extending `MariaDB4jRule` which has a static variable

but why? It's not clear to me what you are trying to achieve...

... would you like MariaDB4j to create a fresh new DB for:

1. each `@Test` annotated method
2. once for each class which has `@Test` annotated methods (but shared among all such methods)
3. one single one shared among all of your test classes

So for 1. you can use the `MariaDB4jRule` as is; for 2. may be making the rule field static helps (not tested), and for 3. I'm guessing a little bit more new work would be needed, probably a separate new rule, or a flag - something like what it seems like you are trying to achieve with that static...

@yiftizur may or may not be motivated to help further with this?

**Comment by yiftizur** [comment]
For #2, use this class as a @ClassRule and then it will be created before all tests, and stopped after all tests... But that is assuming you're OK with handling data between tests...

**Comment by OfekCyberX** [comment]
@vorburger @yiftizur I thought about using @ClassRule, but it doesn't work together with PowerMockRunner, and I need it.
https://stackoverflow.com/questions/38772027/powermockrunner-does-not-apply-junit-classrules

So ideally I would want to init it once for class, and clear it between test methods - but can't use @ClassRule.

So, I used regular @Rule, but I keep getting the "Address already in use" error - which to me sounds like an issue with the mariadb mock not stopping fully.
It doesn't happen always, but it does, so I am looking for a fix that will handle this reoccurring error.

**Comment by vorburger** [comment]
> using @ClassRule, but it doesn't work together with PowerMockRunner

oh. But that's perhaps a pretty... "exotic" combination? MariaDB4j is more IT and PowerMock isn't.

Unfortunately I personally won't the time to help further for this - but others in the MariaDB4j user community who may be reading this issue may want to chime here, so leaving this open; close it when you figured out how to solve your problem! Best of luck.

**Comment by yiftizur** [comment]
@OfekCyberX Can you use the MariaDB4jRule as it is with the constructor:
`@Rule MariaDB4jRule db = new MariaDB4jRule(0);`

The for each test, the db will be created on a random port, and even if the previous test db cleanup didn't finish cleanly (for some reason - maybe worth checking if there are any db connections hanging or anything of that sort), the next test will use a different port....

If you need the DB process to be created once for the entire class, and run with the powermock runner, did you try the suggestion in that stackoverflow thread (using `PowerMockRunnerDelegate` to use the JunitRunner) ?

If all fails, maybe simply use the DB directly in the Class Setup?
`
public class TestDBTest {


    private static DB db;

    @BeforeClass
    public static void setupDB() throws ManagedProcessException {
        DBConfigurationBuilder builder = DBConfigurationBuilder.newBuilder().setPort(0).addArg("--character-set-server=latin1");
        db = DB.newEmbeddedDB(builder.build());
        db.start();
    }

    @AfterClass
    public static void stopDB() throws ManagedProcessException {
        db.stop();
    }

    @Test
    public void test1() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test2() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test3() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test4() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test5() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test6() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test7() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test8() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test9() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test10() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test11() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test12() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test13() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }

    @Test
    public void test14() {
        System.out.println(db.getConfiguration().getURL("foo"));
    }
}

`

**Comment by vorburger** [comment]
@OfekCyberX could #95 be useful for you re. this?

**Comment by liuguofeng719** [comment]
@OfekCyberX "Address already in use", fix ?

**Comment by liuguofeng719** [comment]
@vorburger "Address already in use" when trying to start DB, Is now the problem solved?
