### ISSUE TITLE
Missing documentation for new MariaDB4jRule

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#219]
The [just released MariaDB4j v2.4.0](https://github.com/vorburger/MariaDB4j/blob/master/CHANGELOG.md) includes a cool new [MariaDB4jRule](https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/junit/MariaDB4jRule.java) JUnit rule which @yiftizur contributed.

Our README does not mention this yet. @OfekCyberX @yiftizur would you be willing to contribute to this project with a PR that adds documentation about the MariaDB4jRule to the README?

Let's stick to document what we have and how it works today. (The stuff discussed in #214 is for the future and this documentation could get updated later with whatever you figure out there.)

**Comment by yiftizur** [comment]
Hey @vorburger I'll be happy to do that :) ill try to add it in the coming weekend :)

**Comment by vorburger** [comment]
@yiftizur ping ;) still thing your JUnit rule would benefit from doc in the README...

**Comment by vorburger** [comment]
https://github.com/vorburger/MariaDB4j#junit-integration
