### ISSUE TITLE
Complete README,describe detail about MariaDB4j

### ISSUE THREAD

**Issue by wenerme** [vorburger/MariaDB4j#22]
MariaDB versions in each platform ?
Change logs ?

**Comment by vorburger** [comment]
Hi @wenerme thanks for your interest!

You can see the exact current version of MariaDB used for each platform in https://github.com/vorburger/MariaDB4j/tree/master/src/main/resources/ch/vorburger/mariadb4j. Also note https://github.com/vorburger/MariaDB4j/issues/9 which I'll do one day (if you would like to contribute via a pull request, that would be cool).

Change log of MariaDB4j is in https://github.com/vorburger/MariaDB4j/blob/master/CHANGES.md. Change Log for MariaDB itself can be found somewhere on https://mariadb.org.

What other detail about MariaDB4j are you interested in?

**Comment by wenerme** [comment]
can not custom mariadb parameter, no my.cnf can use.
I want to use this to test my replication protocol, but can not use grant.no replication user.can not set the binlog etc...
I also want to test the failover of my application, is't too complex to use real db.
Why I choose the mariadb4j, because it's special things I want to use , not only execute sql(H2 is best for test).

So, is this possible for mariadb4j ? any plan ?

**Comment by vorburger** [comment]
@wenerme With https://github.com/vorburger/MariaDB4j/pull/23 it is now possible to add custom mariadb parameters! Does this solve your requirement? OK for you to close this issue (which is a bit generic, perhaps you could open more specific follow-up issues if you have other feedback) ?

**Comment by wenerme** [comment]
Thanks,I'll try this feature.
