### ISSUE TITLE
MariaDB4j 2.4.0 stuck after shutdown of db

### ISSUE THREAD

**Issue by tenjaa** [vorburger/MariaDB4j#227]
Hello,
we have an issue, that after our test is done (and according to the logs the database shut down) the process just gets stuck. The problem can be reproduces on concourse and also locally.
Everything works fine with 2.3.0.
Do you have any idea or guide how to debug this further?

Components used:
Spring Boot 2.1.3.RELEASE
JUnit 5.3.1
Gradle 5.1.2
OpenJDK 11.0.2 (In concourse docker image openjdk:11, locally installed through sdkman on OSX)

Logs:

`{"@timestamp":"2019-03-05T14:35:59.334+00:00","message":"cleanupOnExit() ShutdownHook now stopping database","logger_name":"ch.vorburger.mariadb4j.DB","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.379+00:00","message":"mysqld: 2019-03-05 14:35:59 140110359561984 [Note] /tmp/MariaDB4j/base/bin/mysqld (unknown): Normal shutdown","logger_name":"ch.vorburger.exec.ManagedProcess","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.379+00:00","message":"mysqld: ","logger_name":"ch.vorburger.exec.ManagedProcess","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.383+00:00","message":"mysqld: 2019-03-05 14:35:59 140109710075648 [Note] InnoDB: FTS optimize thread exiting.","logger_name":"ch.vorburger.exec.ManagedProcess","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.404+00:00","message":"mysqld: 2019-03-05 14:35:59 140110359561984 [Note] InnoDB: Starting shutdown...","logger_name":"ch.vorburger.exec.ManagedProcess","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.406+00:00","message":"mysqld: 2019-03-05 14:35:59 140109609428736 [Note] InnoDB: Dumping buffer pool(s) to /tmp/MariaDB4j/data/40405/ib_buffer_pool","logger_name":"ch.vorburger.exec.ManagedProcess","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.407+00:00","message":"mysqld: 2019-03-05 14:35:59 140109609428736 [Note] InnoDB: Buffer pool(s) dump completed at 190305 14:35:59","logger_name":"ch.vorburger.exec.ManagedProcess","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.476+00:00","message":"Closing JPA EntityManagerFactory for persistence unit 'default'","logger_name":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.476+00:00","message":"Shutting down ExecutorService 'applicationTaskExecutor'","logger_name":"org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.486+00:00","message":"Shutting down ExecutorService 'applicationTaskExecutor'","logger_name":"org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.491+00:00","message":"Shutting down ExecutorService 'applicationTaskExecutor'","logger_name":"org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.495+00:00","message":"Closing JPA EntityManagerFactory for persistence unit 'default'","logger_name":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.501+00:00","message":"Closing JPA EntityManagerFactory for persistence unit 'default'","logger_name":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.509+00:00","message":"Shutting down ExecutorService 'applicationTaskExecutor'","logger_name":"org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.520+00:00","message":"Closing JPA EntityManagerFactory for persistence unit 'default'","logger_name":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.521+00:00","message":"Shutting down ExecutorService 'applicationTaskExecutor'","logger_name":"org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.539+00:00","message":"Shutting down ExecutorService 'applicationTaskExecutor'","logger_name":"org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.545+00:00","message":"Closing JPA EntityManagerFactory for persistence unit 'default'","logger_name":"org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.546+00:00","message":"Shutting down ExecutorService 'applicationTaskExecutor'","logger_name":"org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.586+00:00","message":"Shutting down embedded database: url='jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'","logger_name":"org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.598+00:00","message":"Shutting down embedded database: url='jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'","logger_name":"org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.609+00:00","message":"Shutting down embedded database: url='jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'","logger_name":"org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory","level":"INFO"}
{"@timestamp":"2019-03-05T14:35:59.611+00:00","message":"HikariPool-1 - Shutdown initiated...","logger_name":"com.zaxxer.hikari.HikariDataSource","level":"INFO"}
{"@timestamp":"2019-03-05T14:36:00.225+00:00","message":"HikariPool-1 - Shutdown completed.","logger_name":"com.zaxxer.hikari.HikariDataSource","level":"INFO"}
{"@timestamp":"2019-03-05T14:36:01.118+00:00","message":"Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/40405, --port=40405, --socket=/tmp/MariaDB4j.40405.sock, --user=root] (in working directory /tmp/MariaDB4j/base) just exited, with value 0","logger_name":"ch.vorburger.exec.LoggingExecuteResultHandler","level":"INFO"}
{"@timestamp":"2019-03-05T14:36:01.134+00:00","message":"Successfully destroyed Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/40405, --port=40405, --socket=/tmp/MariaDB4j.40405.sock, --user=root] (in working directory /tmp/MariaDB4j/base)","logger_name":"ch.vorburger.exec.ManagedProcess","level":"INFO"}
{"@timestamp":"2019-03-05T14:36:01.134+00:00","message":"Database stopped.","logger_name":"ch.vorburger.mariadb4j.DB","level":"INFO"}
{"@timestamp":"2019-03-05T14:36:01.134+00:00","message":"cleanupOnExit() ShutdownHook quietly deleting temporary DB data directory: /tmp/MariaDB4j/data/40405","logger_name":"ch.vorburger.mariadb4j.DB","level":"INFO"}
{"@timestamp":"2019-03-05T14:36:01.192+00:00","message":"cleanupOnExit() ShutdownHook quietly deleting temporary DB base directory: /tmp/MariaDB4j/base","logger_name":"ch.vorburger.mariadb4j.DB","level":"INFO"}`

**Comment by vorburger** [comment]
>
> the process just gets stuck
>
That normally happens if you have any non daemon threads which did not
stop... You need to use "jstack" to find them.

This may have nothing to do with MariaDB4j...

**Comment by tenjaa** [comment]
You are probably right. Im going to close this issue for now.
Thanks!
