### ISSUE TITLE
Dynamic package with direct download of mariadb

### ISSUE THREAD

**Issue by srbala** [vorburger/MariaDB4j#230]
@vorburger Is there any reason mariadb binary files to part of project. it would be good idea to get id dynamically and filter necessay during package phase. this would reduce repository size and git file size limits. 

Any dynamically downloaed file needs kept in output/target folder  can be excluede via git ignore.

**Comment by vorburger** [comment]
That is an interesting idea! It's also interesting to do it like that from
a security perspective - instead of trusting binaries in the repo. I would
welcome a Pull Request doing this for a new latest DB binary.  Would you be
willing to work on this?

>

**Comment by srbala** [comment]
> That is an interesting idea! It's also interesting to do it like that from
a security perspective - instead of trusting binaries in the repo.

That was the main goal.

>  I would welcome a Pull Request doing this for a new latest DB binary.  Would you be
willing to work on this?

I'll give it a try. 

For linux and windws download will be from https://downloads.mariadb.com/MariaDB/
For Mac https://bintray.com/homebrew/bottles/mariadb#files since MariaDB no longer release mac versions since 10.2.12

**Comment by vorburger** [comment]
@srbala coincidentally @jtmuhone just raised #229 with new MariaDB 10.3.7 binaries .. if you are about to propose a PR here doing it this way, that could be very interesting - otherwise I'll merge that. Or perhaps this could be an opportunity for you and @srbala and @jtmuhone to work together on this idea for this project? Also note #213 ...

**Comment by srbala** [comment]
@vorburger  I am progressing on my PR. I see multiple flavours of linux files to download on https://downloads.mariadb.com/MariaDB/mariadb-10.3.13/ which one needs to choosed?

**Comment by vorburger** [comment]
> @vorburger I am progressing on my PR. I see multiple flavours of linux files to download on https://downloads.mariadb.com/MariaDB/mariadb-10.3.13/ which one needs to choosed?

If I had to guess, I would say the `/bintar-linux-x86_64/` looks like what you want? But I'd love @jtmuhone to chime in here (and work with you / help you / test your work) and let us know to double check and confirm where he got the binaries he used in #229 from? Of course, you can raise your PR for review already, and we can always tweak the URL later...

BTW note, quote: _"MacOS binaries have been compiled from source on MacOS 11.2.6 Sierra VirtualBox machine."_ - is really nobody out theremaking MacOS binaries of MariaDB? Perhaps worth asking around about on some... MariaDB Forum/ StackOverflow? Let's first get Linux and Windows binaries sorted out, and then worry about Mac.

**Comment by srbala** [comment]
Greate, right now I am already working with `/bintar-linux-x86_64/`, so I'm good. 

I have used https://bintray.com/homebrew/bottles/mariadb#files on my WIP. MacOS 12/13 available from there too, it's matter of fixing URL.

**Comment by srbala** [comment]
@vorburger Done with my PR changes, testing in progress https://github.com/srbala/MariaDB4j/commit/835d04e7418ea93d81a4ace533b1ff7ff7f1b199
@jtmuhone My changes are in https://github.com/srbala/MariaDB4j/tree/feat-231 would be able to some testing?
