### ISSUE TITLE
MariaDB4j/DBs folder reorg to support multiple versions of mariadb

### ISSUE THREAD

**Issue by srbala** [vorburger/MariaDB4j#231]
@vorburger MariaDB4j/DBs reorg to better hanlding of mariadb versions, if you are interested, I can work on a PR

MariaDB4j/DBs/linux
MariaDB4j/DBs/linux/mariadb-10.1  - points to latest patch release of 10.1.x
MariaDB4j/DBs/linux/mariadb-10.2  - points to latest patch release of 10.2.x
MariaDB4j/DBs/linux/mariadb-10.3  - points to latest patch release of 10.3.x

Similar folder structure for Mac and Windows.

With dynamic package, #230 
users older versions of OSs can use older verions of mariadb

**Comment by vorburger** [comment]
For reproducibility of old versions, I would prefer to keep the current structure with the fixed versions, instead of a pointer that switches over time. Hope that's OK with you - close this issue?

**Comment by srbala** [comment]
@vorburger I understand your point.

I used following structure for my PR #235, it works for unit testing specific version of DB
 
MariaDB4j/DBs/mariaDB4j-db-10.3/
MariaDB4j/DBs/mariaDB4j-db-10.3/mariaDB4j-db-linux64-10.3
MariaDB4j/DBs/mariaDB4j-db-10.3/mariaDB4j-db-mac64-10.3
MariaDB4j/DBs/mariaDB4j-db-10.3/mariaDB4j-db-win32-10.3

Planning to create new PRs for older version latest releases
