### ISSUE TITLE
Support sending inputStream directly to source()

### ISSUE THREAD

**Issue by Molyna** [vorburger/MariaDB4j#243]
Currently the only way to source the the database is by accessing the file system based on the classpath. However for better coverage I would like to suggest supporting sending an inputStream to the source methods instead of just a file path. This can at least help in cases where there needs to be some special handling on the file before sending it to the system. There are probably more use cases for this as well.

Requirements for this should be simple as all the source methods just wrap on a protected run method.

**Comment by vorburger** [comment]
@Molyna any useful contributions to this open source project via Pull Requests are very welcome!

**Comment by Molyna** [comment]
Sure, I'll get one sorted over the next few days.

**Comment by vorburger** [comment]
@asbachb contributed this in #274 for #273.
