### ISSUE TITLE
[Maven] spring.version property needs to be declared even when not using spring

### ISSUE THREAD

**Issue by mdindoffer** [vorburger/MariaDB4j#247]
MariaDB4j [uses](https://github.com/vorburger/MariaDB4j/blob/cb1eb92b8804a6e49b120c4274ca8b476ab0c50b/pom.xml#L43) `spring.version` property for `spring-core` dependency.

We use MariaDB4j in a library artefact, that gets BOM-imported into other parts of the application. This fails without redeclaring the `spring.version` property in the final destination POM:
```
[ERROR] Failed to execute goal on project example-impl: Could not resolve dependencies for project com.example:example-impl:jar:1.5.0-SNAPSHOT: Failed to collect dependencies at com.example:example-rest-client:jar:1.7.0-SNAPSHOT -> com.example:common-test:jar:1.15.0-SNAPSHOT -> ch.vorburger.mariaDB4j:mariaDB4j:jar:2.3.0 -> ch.vorburger.mariaDB4j:mariaDB4j-core:jar:2.3.0 -> org.springframework:spring-core:jar:${spring.version}: Failed to read artifact descriptor for org.springframework:spring-core:jar:${spring.version}: Could not transfer artifact org.springframework:spring-core:pom:${spring.version} from/to nexus (http://nexus.example.com:8081/repository/public/): Failed to transfer file: http://nexus.example.com:8081/repository/public/org/springframework/spring-core/$%7Bspring.version%7D/spring-core-$%7Bspring.version%7D.pom. Return code is: 400 , ReasonPhrase:Invalid repository path. -> [Help 1]
```

Maven POM import:
```xml
<type>pom</type>
<scope>import</scope>
```
typically used as a BOM-import pattern does not import Maven properties. `import` imports only management sections of the pom file. 

Redeclaring the version is an ugly workaround, because our application does not depend on spring in any way.
This probably can be fixed by simply not using the property version declarations, and using the `<dependencyManagement>` instead.

**Comment by vorburger** [comment]
> Redeclaring the version is an ugly workaround, because our application does not depend on spring in any way.

I agree, makes sense. 

>  This probably can be fixed by simply not using the property version declarations, and using the <dependencyManagement> instead.

Would you be willing to support this project which you use by raising a PR which does this?

**Comment by mdindoffer** [comment]
Actually, I take that back. It looks like the issue was on our side.
However, I've found out that the spring.version property gets overriden anyway by the springboot import, so it is useless. Will make a PR shortly.
