### ISSUE TITLE
DB.run - Continue on error

### ISSUE THREAD

**Issue by glittle1972** [vorburger/MariaDB4j#259]
I have a use case where a vendor supplies a long list of DDL or SQL statements for installation/upgrade. Depending on the starting version, table updates may fail because, for example, a column already exists. Their instructions are to ensure your SQL client is configured to "continue on error". In mysql, this would involve using the `--force` argument.

I'm applying the script using DB.run(command, username, password, database) (v2.4.0)

Is there a way to define the `--force` argument before calling run(), or supply it to the method? 
I tried fudging it by adding " -f" to the end of my username but no dice :) 

I'm happy to try creating a pull request if you can confirm I'm not missing an existing solution.

Thanks, Gordon

**Comment by glittle1972** [comment]
Do I have responsibility for closing this issue now the accompanying PR has been merged? 

Thanks, Gordon

**Comment by vorburger** [comment]
Yes, you are more than welcome to close issues. (Like wise you can help the project by reviewing old issues and commenting on what you think could be closed now.)

Pro Tip: If your commit message is '"bla (fixes #259)" then GitHub does it automatically for you.
