### ISSUE TITLE
Enforce Checkstyle and amend ruleset

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#264]
Make Checkstyle violations fail the build and not just emit warnings.

Amend [/checkstyle.xml](https://github.com/vorburger/MariaDB4j/blob/master/checkstyle.xml) with [the Checkstyle Rules from OpenDaylight.org](https://github.com/opendaylight/odlparent/blob/master/checkstyle/src/main/resources/odl_checks.xml) (which significantly contributed to shaping).

This will "do away" with issues such as #240 or my formatting nit pit reviews e.g. in #260.

**Comment by vorburger** [comment]
fix #257 first..

This would be a great issue for anyone who like to start contribute to the project - see #213.

**Comment by vorburger** [comment]
I've stumbled upon this again today while reviewing #417.

After all this time I had assumed CS was enabled, but it's actually currently ignored.

https://github.com/vorburger/MariaDB4j/compare/bump-checkstyle has some related WIP, but it would need more work.

@glittle1972 would this potentially interest you to contribute to this project again, given your past #271?

**Comment by glittle1972** [comment]
@vorburger - I can spend some time on this. 

What's the current status? I see the original intent is to fail the build but I don't think that's happening at the moment?
And you state above that you think cs is disabled but I can see around 54 WARN messages? 

Would you like all warnings promoted to errors and any failures addressed?
I may need to come back to you whether a violation
* should not be in the checkstyle policy at all
* should be a specific exception to the policy
* needs input to provide text for documentation, for example

**Comment by vorburger** [comment]
> What's the current status? I see the original intent is to fail the build but I don't think that's happening at the moment?

Correct. My experience over the years has been that "warnings don't work", and only "enforcement" (to fail the build on PRs) is effective. The trick, if required, is typically to start enforcing a reasonable subset of such code quality criteria - and then (if desired) gradually improve on it incrementally.

> And you state above that you think cs is disabled but I can see around 54 WARN messages?

Yeah on my https://github.com/vorburger/MariaDB4j/compare/bump-checkstyle I also see these same WARN messages. I suggest that the goal of this PR should be to take that branch, make all warnings to be errors that fail the build, and address any of the trivial problems on that branch/PR, and deactivate some other ones.

> Would you like all warnings promoted to errors and any failures addressed?

Yes but I think it's fair to not have to see ALL failures addressed and deactivate some checks.

> I may need to come back to you whether a violation 

How about focusing on everything else BUT JavaDoc - and then perhaps work on improved JavaDoc later separately, AFTER enforcement is enabled for everything else?

An alternative to supressing anything that doesn't fail the build could be to keep e.g. JavaDoc (and maybe some others that are non-trivial to just address) as WARN and the rest as errors that fail that build, but my experience has been that that's actually not really that useful.

**Comment by glittle1972** [comment]
OK, great. Almost done. 

The only other rule wanting a lot of fixes is CustomImportOrder that wants to reorder all your import statements. It wants to turn:
```
import java.io.IOException; 

import ch.vorburger.exec.ManagedProcessException;
import ch.vorburger.mariadb4j.utils.DBSingleton;

import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.ResolutionScope;
```
into
```
import ch.vorburger.exec.ManagedProcessException;
import ch.vorburger.mariadb4j.utils.DBSingleton;
import java.io.IOException;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.ResolutionScope;
```
I think it's better how you have it already, *and* is how the rule is meant to work by default. 
I suspect the rule has been defined incorrectly and by adding the "sortAlphabeticallyWithinGroups" flag on its own, this removes the default behaviour (grouping STATIC, SAME_PACKAGE, THIRD_PARTY...). Would you like to keep the groups, but sort *within* groups?

**Comment by glittle1972** [comment]
Great explanation, I'm still in 2017.
