### ISSUE TITLE
[Question] SqlDialectInspection

### ISSUE THREAD

**Issue by glittle1972** [vorburger/MariaDB4j#265]
I was looking at making a PR to remove some of the annoying build problems I was seeing (use of deprecated methods, unused imports...).

I'm using vscode and getting Problems regarding @SuppressWarnings("SqlDialectInspection") and "SqlNoDataSourceInspection" but I don't recognise SqlDialectInspection from my Eclipse experience. I found some Intellij IDEAs references but nothing explaining its purpose.

Are these SQL related @SuppressWarnings safe to remove? Does it depend on compiler, IDE, some plugin? Just want to check before making an unnecessary or incorrect change.

Thanks, Gordon

**Comment by vorburger** [comment]
No clue.

Use Git History to see who added them, and then tag them here to ask

Googling "java SqlDialectInspection" seems to indicate that this is an
IntelliJ thing.

VS Code should just ignore any unknown Suppress Warnings. Perhaps you can
configure it to do so?

>

**Comment by glittle1972** [comment]
@duttonw, @vorburger  - Could someone explain the potential impact of removing the SqlDialectInspection and SqlNoDataSourceInspection SuppressWarnings in, for example, mariaDB4j-maven-plugin/src/test/java/ch/vorburger/mariaDB4j/DbUtils.java(40)

These lines raise Unsupported warnings - e.g. **Unsupported @SuppressWarnings("SqlDialectInspection") - in both Eclipse and VS Code.

It seems like the attempt to suppress warnings in one environment simply raises new warnings in others and that this should be controlled in that environment's settings rather than requiring a source code change.

The options appear to be unique to IDEAs. I've attempted opening the project in 2019.1 Community Edition which does not raise the Unsupported warning, but also does not complain when the SuppressWarnings line is commented out. I suspect the options are specific to having Database and/or SQL plugins installed which don't seem to be available in Community Edition.

If it turns out that everyone but me is using IDEAs Ultimate Edition with SQL plugins, then I will of course just suck it up. :)

**Comment by vorburger** [comment]
I would merge a PR from you removing it.
