### ISSUE TITLE
`DB.source()` should support `InputStream`

### ISSUE THREAD

**Issue by asbachb** [vorburger/MariaDB4j#273]
I guess it would be useful to have an api which enables user to pass an `InputStream` instead of a resourceName in case the resource is not part of the project.

If agreed on project level I can prepare a PR.

**Comment by vorburger** [comment]
Pull Request welcome... ;-)

>

**Comment by asbachb** [comment]
@vorburger I added a PR some time ago. Maybe you can have a give some feedback on it.

**Comment by vorburger** [comment]
#273 finally reviewed and merged.  Thanks for contributing!

Really so very sorry it took this long to review this PR! 

Do please feel free to send more PRs for anything.
