### ISSUE TITLE
splitting the configuration: isDeletingTemporaryBaseAndDataDirsOnShutdown

### ISSUE THREAD

**Issue by shai125** [vorburger/MariaDB4j#279]
Hi,
I would like to split the configuration `isDeletingTemporaryBaseAndDataDirsOnShutdown` to two separate configuration in `DBConfiguration` interface:
`isDeletingTemporaryBaseOnShutdown`
`isDeletingTemporaryDataDirsOnShutdown`

since when we run our build in team city we have several builds that run in parallel, so some build could delete's the base dir of another build.

**Comment by shai125** [comment]
I know that I can set the base dir to a non-temp folder and hence it won't be deleted, but this suggestion is cleaner.

**Comment by vorburger** [comment]
Hello @cleverpig. Thanks for your interest in this project. Pull Requests are most welcome!
