### ISSUE TITLE
How skip the "mysql_install_db" installPreparation process?

### ISSUE THREAD

**Issue by cleverpig** [vorburger/MariaDB4j#281]
I don't need run installPreparation process everytime before db started.

**Comment by cleverpig** [comment]
I worked around by this class:

```
import ch.vorburger.exec.ManagedProcessException;
import ch.vorburger.mariadb4j.DB;
import ch.vorburger.mariadb4j.DBConfiguration;

public class MyMariaDB extends DB {

	protected MyMariaDB(DBConfiguration config) {
		super(config);
	}

	public static MyMariaDB newEmbeddedDB(DBConfiguration config,boolean installDB) throws ManagedProcessException {
		MyMariaDB db = new MyMariaDB(config);
		db.prepareDirectories();
		db.unpackEmbeddedDb();
		if (installDB) {
			db.install();
		}
		return db;
	}
}
```

**Comment by vorburger** [comment]
Hello @cleverpig. Thanks for your interest in this project. Pull Requests are most welcome!

**Comment by sherrif10** [comment]
Hello thanks for working together , Am kinda curios about how we ca replace mariaDB4J onto mysql, could any one guide me of any clues or a link that will provide guides of replacing the embedded mysql with maria4DBJ thanks
