### ISSUE TITLE
Is is possible to use host mariadb-server? 

### ISSUE THREAD

**Issue by stokito** [vorburger/MariaDB4j#284]
My project using the MariaDB4j but I anyway have an installed mariadb server on my computer so can I somehow just reuse it?
I can't use the option `-DmariaDB4j.unpack=false -DmariaDB4j.baseDir=/myFavouritemMariadDBVersion` just because on my Ubuntu the mariadb in installed in several folders (`/usr/lib` etc.)

**Comment by vorburger** [comment]
If you would like to contribute to the project with a PR which adds support for this, that would certainly be welcome.

**Comment by EasyG0ing1** [comment]
> My project using the MariaDB4j but I anyway have an installed mariadb server on my computer so can I somehow just reuse it?
> I can't use the option `-DmariaDB4j.unpack=false -DmariaDB4j.baseDir=/myFavouritemMariadDBVersion` just because on my Ubuntu the mariadb in installed in several folders (`/usr/lib` etc.)

I actually do this with a single Java Class, as long as the folder in workingFolder exists in a place that you have read and create permission (like your users folder) it will create all the needed files on first run. Then you just use any MySQL editor and point it to port 3307 and you're golden!  You can create schema's and do anything you need to with them:

```
import ch.vorburger.exec.ManagedProcessException;
import ch.vorburger.mariadb4j.DBConfigurationBuilder;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.TimeZone;


public class Main extends Application {
	private static ch.vorburger.mariadb4j.DB myDB;
	public static void main(String[] args) {
		try {
			String 	workingFolder 		  = "/Users/michael/JavaApps/EmbeddedMySQL";
			String	jdbcURL               = "jdbc:mysql://";
			String	host                  = "localhost";
			int		port                  = 3307;
			String	schema                = "MyOTPData";
			String	ANNOYING_TIMEZONE_FIX = "?serverTimezone=" + TimeZone.getDefault().getID();
			String	user                  = "root";
			String	password              = "";
			String	slash                 = "/";
			String	colon                 = ":";
			String	connString            = jdbcURL + host + colon + port + slash + schema + ANNOYING_TIMEZONE_FIX;
			DBConfigurationBuilder configBuilder = DBConfigurationBuilder.newBuilder().setPort(port).setDataDir(workingFolder);
			myDB = ch.vorburger.mariadb4j.DB.newEmbeddedDB(configBuilder.build());
			myDB.start();
			myDB.createDB(schema);
			DriverManager.getConnection(connString, user, password);
		}
		catch (SQLException | ManagedProcessException e) {e.printStackTrace();}
	}
}
```

**Comment by vorburger** [comment]
I'm closing this issue, because it's definitely possible to use host DB binaries. It's documented on the README (and PRs to clarify doc if it could be clearer are always welcome). #416 has something related to this.
