### ISSUE TITLE
mysql_install_db script takes an inconsistent amount of time to terminate self

### ISSUE THREAD

**Issue by Anthoknee** [vorburger/MariaDB4j#287]
Hello, 

In the CI process for our app, we are seeing an inconsistency in terms of how long it takes for `mysql_install_db` to terminate itself when using `DB.newEmbeddedDB`. This is becoming an issue as it makes the timed health check flaky. 

I have seen anywhere between 5 seconds and over 2 and a half minutes, as below. 

Is there any known reason for this inconsistency? 

Example log of a longer termination below:

```
2019/08/27 18:16:09.431 INFO [ManagedProcess] [main] [application] [] Thread is now going to wait for this process to terminate itself: Program [/export/content/apps/application/tmp/MariaDB4j/base/scripts/mysql_install_db, --datadir=
/export/content/apps/application/tmp/MariaDB4j/data/9653, --basedir=/export/content/apps/application/tmp/MariaDB4j/base, --no-defaults, --force, --skip-name-resolve] (in working directory /export/content/apps/application/tmp/MariaDB4j/base)
2019/08/27 18:16:09.641 INFO [ManagedProcess] [Exec Stream Pumper] [application] [] mysql_install_db: Installing MariaDB/MySQL system tables in '/export/content/apps/application/tmp/MariaDB4j/data/9653' ...
2019/08/27 18:18:46.946 INFO [ManagedProcess] [Exec Stream Pumper] [application] [] mysql_install_db: OK
```

**Comment by vorburger** [comment]
I don't suppose #285 would help?

If not, you'll have to debug it, and maybe raise a PR with an Improvement?

Please support this project via the Sponsor button.

**Comment by Anthoknee** [comment]
#285 unfortunately does not help. 

I've tried debugging the various SQL statements that are run and have been unable to pinpoint one specific statement that causes this to hang. mysql_system_tables_data does throw an error on insertion where `ssl_cipher`, `x509_issuer`, `x509_subject`, and `authentication_string` do not have defined defaults. Even after updating those, it seems to hang on different parts of the install intermittently. 

I ran the script 400 times with different install directories and found times between 5 and 61 seconds, with an average of about 11.22 seconds on my machine.

My proposed fix would be to:

1. Add defaults to the script that are missing values as per above
2. Have a timeout and number of attempts on the install script that is configurable. If not defined, it will just wait for the exit (current behavior). 

To do this: 
1. Add a `destroyed` flag to `ManagedProcess` (watchdog doesn't seem to set this)
2. Add the attempt loop to `DB`, if timeout and attempts are defined. 

Does this seem reasonable to you? Any further suggestions?

**Comment by Anthoknee** [comment]
I have created: https://github.com/vorburger/MariaDB4j/pull/299 and https://github.com/vorburger/ch.vorburger.exec/pull/28 to attempt to alleviate some of this issue.

**Comment by vorburger** [comment]
@Anthoknee is this OK to close now?
