### ISSUE TITLE
How do you create a new schema (and/or user, permissions, etc) when using MariaDB4j with Spring Boot?

### ISSUE THREAD

**Issue by steve-perkins** [vorburger/MariaDB4j#322]
I have been exploring the `mariaDB4j-springboot` dependency, and the sample Spring Boot application that demonstrates it.  

I notice that the sample application uses the JDBC URL `jdbc:mariadb://localhost:${mariaDB4j.port}/test`.  Which works, because **MariaDB always comes with a "test" schema** available by default.

**However, what about use of a different database/schema?**  In my case, I'm writing integration tests for a Spring Boot microservice that uses Flyway to create all of the tables at startup.  It also expects to connect to the database with a username possessing only a limited set of permissions.

Spring Boot doesn't really have a mechanism for creating a new database or user *before* establishing the `DataSource` connection.  It expects that the JDBC URL you place in your `application.properties` or `application.yml` will already be valid and ready for connections.  So **unless you're using the "test" schema, I don't see how this could ever work.**  Is that an implied assumption with `mariaDB4j-springboot`, that users will always be using the "test" schema with the "root" user?

I could roll my own solution.  Having my test suite manually override the creation of the `DataSource` Spring bean.  And place logic in that override `@Bean` method, to programmatically create the schema and user prior to returning the `DataSource`.

However, rolling your own solution in this manner would seem to defeat the entire purpose of using `mariaDB4j-springboot`.  Might as well just use the core dependency, then.  Am I missing something?  Is there a correct way to do this that fits in with Spring Boot conventions?  Thanks!

**Comment by membersound** [comment]
If you're fine starting the database on your own, try as follows. I'm also using this:
```
public class TableRule implements BeforeAllCallback, AfterAllCallback {
	public TableRule(String table, String sql) {
		this.table = table;
		this.sql = sql;
	}

        @Override
	public void beforeAll(ExtensionContext extensionContext) throws Exception {
		db = new MariaDB4jSpringService();
		db.setDefaultPort(port);
		db.start();

		db.getDB().createDB(table); //CREATE TABLE IF NOT EXISTS...
		db.getDB().source(sql);
	}

	@Override
	public void afterAll(ExtensionContext extensionContext) {
		db.stop();
	}
}


@SpringBootTest
public class TestClass {
	@RegisterExtension
	static TableRule DB = new TableRule("yourtable", "schema.sql");
}
```
