### ISSUE TITLE
JPA : Error Required a bean named 'entityManagerFactory' that could not be found.

### ISSUE THREAD

**Issue by jathoo** [vorburger/MariaDB4j#330]
Hi , 

I am tying to use MariaDB4j as an Embedded database  

I have a config file like this 

` @Bean
    public MariaDB4jSpringService mariaDB4j() {
        return new MariaDB4jSpringService();
    }`

with a property file 
`spring.datasource.url=jdbc:mariadb://localhost:3307/test
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
`

and i am trying to use this library with JpaRepository , but i am getting this error 
`required a bean named 'entityManagerFactory' that could not be found.`

(it works fine with h2 database) 

can anyone help me on what i am doing wrong ? apologies  if this is not the place to ask this question. i would really appreciate any help .

**Comment by vorburger** [comment]
Hello! 

Thank you for your interest in this project. 

The problem you are raising here isn't particular specific to MariaDB4j, but more of a general Java question.

I'm unfortunately unable to offer you support for this particular problem, but have full faith that you will be able to figure this out by searching online.

I'll therefore be closing this issue. Please comment if you disagree and opine that this is an issue with this project (the MariaDB4j Java library).

M.
