### ISSUE TITLE
Release next version 2.5.0

### ISSUE THREAD

**Issue by egwepas** [vorburger/MariaDB4j#334]
Hello, this is a simple question : do you have any plan to release new version with latest fixes (especially the spaces in windows pathes in my case).

In all cases thanks for your helpful tool !

**Comment by xeester** [comment]
Hello, same concern for me : fixing problems with spaces in windows pathes would be very great!
Thank you!

**Comment by vorburger** [comment]
@egwepas @xeester do you want to raise a PR to help fix the broken build? See #451.

**Comment by vorburger** [comment]
OK so I'm piecing from memory where I left this off:

The test failure in #451 is but only blocker which needs to be addressed before a release.

I'm also hitting #452, but that's probably just a local issue for me, which I can separately fix.

For a local build, I first needed to `mvn install` the "new" (cough) `MariaDB4j/DBs/mariaDB4j-db-10.3`. That will have to be deployed, first.

For #372, I then need to `mvn deploy` a new cut of https://github.com/vorburger/ch.vorburger.exec.

Only then as final next step I can deploy a new version of MariaDB4j itself.

But first I have to set up my GPG key to be able to deploy to Maven central again! It's been a while.

**Comment by valdo404** [comment]
Hi, still no release ? How can we help ?

**Comment by vorburger** [comment]
@valdo404 et al reading along here, please [Sponsor my maintenance this project](https://github.com/sponsors/vorburger)! 

It's purely symbolic - but I would appreciate it.

**Comment by vorburger** [comment]
@valdo404 et al reading along here, a 2.5.0 release is currently blocked by #488. Contributions welcome.

**Comment by vorburger** [comment]
Release 2.5.0 has just been pushed to [Maven Central](https://mvnrepository.com/artifact/ch.vorburger.mariaDB4j/mariaDB4j). It should appear on a mirror near you shortly (but it can take at least a few hours).

**Comment by vorburger** [comment]
https://search.maven.org/artifact/ch.vorburger.mariaDB4j/mariaDB4j/2.5.0/jar shows it now.

https://mvnrepository.com/artifact/ch.vorburger.mariaDB4j/mariaDB4j does not show it yet (just about 24h after the release), but that site probably just take a bit longer to update.

**Comment by vorburger** [comment]
https://twitter.com/vorburger/status/1465115301960470531
