### ISSUE TITLE
Please release a new version with MariaDB 10.3

### ISSUE THREAD

**Issue by JD-CSTx** [vorburger/MariaDB4j#336]
If you have complex SQL VIEWS MariaDB 10.3 is already the solution. MariaDB 10.2 can't handle that.
But: MariaDB 10.3 is already working in your code.
Why not release a MariaDB4j 2.4.1 intermediate version on Maven Central?
MariaDB 10.4 support can come later at anytime. :-)

PS: Please include my tiny pull-request #335 before the release.

**Comment by SuyogPaatil** [comment]
@JD-CSTx Can you please tag this issue with 'helpwanted' as mentioned in Readme.md just to get this issue highlighted

**Comment by sherrif10** [comment]
cc @vorburger

**Comment by JD-CSTx** [comment]
> @JD-CSTx Can you please tag this issue with 'helpwanted' as mentioned in Readme.md just to get this issue highlighted
I'm not so sure. I don't need any help, @vorburger just needs to be convinced to release the current code, as it is, just as a 2.4.1 version.

**Comment by vorburger** [comment]
watch #334

**Comment by vorburger** [comment]
#334 released v2.5.0, but FYI #484.
