### ISSUE TITLE
Need to run mysqld as "root"

### ISSUE THREAD

**Issue by lpearson05** [vorburger/MariaDB4j#34]
https://mariadb.com/kb/en/mariadb/running-mysqld-as-root/

Is it addressed by 8da9aa631409a7a2416cf892c4f08fc3675c05be? I'm using docker. I'm about to look into the viability of just having a mysql container and talking to localhost. Already looked into running as a non-root user. No dice.

Update: I think I've figured out how to do a non-root run.

**Comment by vorburger** [comment]
Hello Leora, thanks for your interest in my MariaDB4j! I'm afraid I'm
unclear exactly what bug you are reporting, if any, via this issue? If you
use Docker, as in only mysql/MariaDB in a container, without any Java
along, then MariaDB4j is most likely not a fit / not needed, it makes more
sense embedded in a real Java application (in same container, if Docker).
Perhaps you would like to close this issue you raised, if it works for you
now, to clarify that you don't need any follow up anymore?

**Comment by lpearson05** [comment]
Hi Michael,

You're welcome. Thank you for sharing this.

I'm not reporting a bug. It was a feature request, I guess. Also, I'm not using it standalone in a container. I'm using it during testing, the docker container just providing the deployment environment. Is there some other place to post feature requests?


Thank you for the reply!

**Comment by vorburger** [comment]
@lpearson05 it's perfectly fine to raise feature requests here, it's more that I haven't quite understood what exactly you are suggesting.. so for some reason you would like to run mysqld as root (I'm not sure that's such a great idea - but your call!), from MariaDB4j? Doesn't that "just automatically happen" (I have NOT tried it!) if your Java process already runs as root? Or are you suggesting some API option for a sudo, or something like that? You certainly could use getMysqldArgs().add(whatever you need to make it run with root) ..

**Comment by lpearson05** [comment]
@vorburger I think I'm basically asking about `getMysqldArgs.add()`. I didn't _want_ to run as root. That's just the default user inside the docker container, and I didn't want to switch away from that if I didn't have to. (Docker's root user is not real root, anyway, by the way.)

Also, yes, the process does run as root. That's the problem. Mysqld doesn't want to be run as root. It prints `"Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!"` if you run it as root, unless some override is set.

**Comment by wuranbo** [comment]
@vorburger , thanks your brilliant MariaDB4j, It help me very much. 

I got the similar problem, the error message is: 

2016-12-26 15:59:27 140556976453472 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.1.13-MariaDB) starting as process 10577 ...
2016-12-26 15:59:27 140556976453472 [ERROR] Fatal error: Please consult the Knowledge Base to find out how to run mysqld as root!

when I run it with root user. How can I avoid it.

**Comment by Dinduks** [comment]
For those looking for a quick and simple answer, here's how to create a database that _can_ run as root (beware, Scala code):

```scala
val embeddedDB = {
  val config = DBConfigurationBuilder.newBuilder()
  config.setPort(3306)
  config.addArg("--user=root")
  ch.vorburger.mariadb4j.DB.newEmbeddedDB(config.build())
}
```

**Comment by mokus** [comment]
Any ideas how to do the same if you start mariadb4j from the command line?
like `java mariaDB4j.jar`
