### ISSUE TITLE
Output file resources not closed when using DB.dump

### ISSUE THREAD

**Issue by xipgroc** [vorburger/MariaDB4j#340]
Hello,

we are having a problem when using this excellent library to generate a dump of the local data with the provided wrapper to mysqldump (DB.dump).

We need to manipulate the exported data and afterwards, delete the file. However this is not possible in Windows (in linux it works ok), due to the fact that windows doesn't allow to delete opened files. Even using deleteOnExit fails to delete the file (it works ok on other created files).

I suspect that inside DB.dump, a BufferedOutputStream gets created but never really closed, and this causes delete/deleteOnExit to fail, as when it is run the file is still "open"/(not released).

Inside DB.dump:
`builder.addStdOut(new BufferedOutputStream(new FileOutputStream(outputFile)));`

This is a sample of how we use the library to dump data and how we try to delete the file, the file remains open on program exit (afterwards, it can be deleted manually without problem)

```kotlin
val outputFile = File("filepath.sql")
val dumpProcess = db.dumpSQL(outputFile, dbName, user, password)
dumpProcess.start()
dumpProcess.waitForExit()
outputFile.deleteOnExit()
// Manipulate outputFile etc
```

**Comment by vorburger** [comment]
Oh wow, well spotted, thanks for reporting this. A Pull Request from you
contributing the required fix to correctly close both streams would be much
appreciated!

**Comment by xipgroc** [comment]
I'll see what I can do in some weeks time, right now I'm really busy at work and we managed to work around the problem in our desktop app by deleting the temp dump files on the next program execution instead of on program exit.
