### ISSUE TITLE
Error while start db on Linux machine but it works on windows normally

### ISSUE THREAD

**Issue by zjy5755202** [vorburger/MariaDB4j#342]
When I run my program on winsows, the db start normally, but when I start db on linux machine, something is wrong with db start like this.

![image](https://user-images.githubusercontent.com/32031556/76702905-75aea300-6708-11ea-9e25-9580b0859a69.png)

 
![微信图片_20200315220658](https://user-images.githubusercontent.com/32031556/76703140-4436d700-670a-11ea-983d-e7852c1b3a38.png)

I look up for solution, someone says I should use this command to start db to fix this.

`/usr/sbin/mysqld --user=root
`

But I don't know how to solve the problem in my code. I can not find a function looks like start(String command) to fix this problem

**Comment by vorburger** [comment]
Could you please post the entire log as text instead of screenshot to this
bug? Use a "code block" markdown. That makes it easier to read (and it can
be searched for).

>

**Comment by zjy5755202** [comment]
Here is my log. The error occurred when I invoke db.start.
Thanks a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Michael Vorburger ⛑️"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 凌晨0:58
收件人:&nbsp;"vorburger/MariaDB4j"<MariaDB4j@noreply.github.com&gt;;
抄送:&nbsp;"朱江源"<1181370590@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vorburger/MariaDB4j] Error while start db on Linux machine but it works on windows normally (#342)





 Could you please post the entire log as text instead of screenshot to this
 bug? Use a "code block" markdown. That makes it easier to read (and it can
 be searched for).
 
 &gt;

**Comment by JD-CSTx** [comment]
Use something like:
      DBConfigurationBuilder config = DBConfigurationBuilder.newBuilder();
      config.setPort(PORT);
      config.addArg("--user=root");
      DB db = DB.newEmbeddedDB(config.build());

**Comment by vorburger** [comment]
Can this issue be closed?

**Comment by JD-CSTx** [comment]
@vorburger I guess so?
Happy to see you are still in the project. I was fearing you abandoned it, since the last release was over a year ago.
