### ISSUE TITLE
Can I stop MariaDB4j from adding spring.jcl ? 

### ISSUE THREAD

**Issue by AdelDima** [vorburger/MariaDB4j#357]
Hi,
I'm working on JavaFX project with maven and Java 11, so I'm using module-info.java to package up my Java application and Java packages into Java modules.

The issue is MariaDB4j  added **spring.jcl** on dependencies this is shy I'm getting this error 
```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules spring.jcl and commons.logging export package org.apache.commons.logging to module javafx.baseEmpty

```
After deleting spring.jcl my application works again, but each time I made a change on pom.xnl the package spring.jcl gets added automatically by MariaDB4j  .
Thank You!

**Comment by vorburger** [comment]
Hello! 

Thank you for your interest in this project. 

You raise a fair point. If you would like to contribute to this project, please raise a Pull Request about this.

M.
