### ISSUE TITLE
Don't delete baseDir when it is set to /tmp/

### ISSUE THREAD

**Issue by simonft** [vorburger/MariaDB4j#36]
Currently [cleanupOnExit](https://github.com/vorburger/MariaDB4j/blob/9848055af3a10484134c3f3d6b81ed17d14dd77f/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java#L355) deletes the baseDir if it thinks it is a temporary directory, which is determined with [isTemporaryDirectory](https://github.com/vorburger/MariaDB4j/blob/9848055af3a10484134c3f3d6b81ed17d14dd77f/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/Util.java#L89).

isTemoraryDirectory uses directory.startsWith(SystemUtils.JAVA_IO_TMPDIR) to determine whether it is a "temporary directory". I think there might be two different definitions of temporary directory used here though. cleanupOnExit should delete the baseDir if it is a directory which is temporary, as in around only for a short period of time. SystemUtils.JAVA_IO_TMPDIR will tell you if it is a directory for storing temporary files, not if it's a directory that can be removed without issue. The best example of this is '/tmp/', which is what we had it set to.

In fact, cleanupOnExit should not delete any directories it has not created itself.

**Comment by vorburger** [comment]
I see what you mean. Would you be willing to contribute to the project and
put in a pull request with a suggested change? I'd definitely look at it
for possible merge.

You can also subclass it and override isTemporaryDirectory - I've
intentionally made it a protected for this.. ;-)

**Comment by vorburger** [comment]
@simonft if you would like to contribute a PR with what you had in mind above, I'd certainly look at it... I just tried a quick implementation myself, but "should not delete any directories it has not created itself", which does sound good to me, is not 1 line trivial change to implement, what would be the exact criteria for you for "it has not created itself" ? For the baseDir, would it be if a call through installPreparation() ? Or unpackEmbeddedDb() ? For dataDir, would it be .. what, createDB() ? Nah, that's not reliable / what you want. Hm.

**Comment by paulroemer** [comment]
What about letting the user decide if he/she wants to delete the directory during shutdown. Wouldn't it be much more easier to just add an option to the configuration?

```configBuilder.setKeepDataDir()```

**Comment by vorburger** [comment]
@paulroemer that would work for me .. for backwards compat. perhaps the default should be to behave as it's now, but users of a new version could change it via the setter on configuration?

**Comment by vorburger** [comment]
https://github.com/vorburger/MariaDB4j/pull/84 adds a new `setDeletingTemporaryBaseAndDataDirsOnShutdown(false)` to do this; TX to @paulroemer 

[Standard Footer] PS: Shameless plug, consider https://www.patreon.com/vorburger to support MariaDB4j.
