### ISSUE TITLE
MariaDB4j does not stop when kill spring-boot

### ISSUE THREAD

**Issue by rodolfotva** [vorburger/MariaDB4j#364]
Hi,

When I kill my spring-boot in Eclipse the MariaDB keep running until I kill the windows task mysqld.

Someone has any Idea why?

thanks

**Comment by Tomlincoln** [comment]
Hi @rodolfotva ,

Have a look here:
[https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDB4jService.java#L104]

**Comment by Tomlincoln** [comment]
Hi @rodolfotva ,

Have a look:

`public static void main(String[] args) throws Exception {
        MariaDB4jService service = new MariaDB4jService();
        service.start();

        waitForKeyPressToCleanlyExit();

        // NOTE: In Eclipse, the MariaDB4j Shutdown Hook is not invoked on
        // exit.. so: (@see https://bugs.eclipse.org/bugs/show_bug.cgi?id=38016)
        service.stop();
    }`

(MariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDB4jService.java)

**Comment by Tomlincoln** [comment]
Hi @rodolfotva ,

Have a look :)

```
public static void main(String[] args) throws Exception {
        MariaDB4jService service = new MariaDB4jService();
        service.start();

        waitForKeyPressToCleanlyExit();

        // NOTE: In Eclipse, the MariaDB4j Shutdown Hook is not invoked on
        // exit.. so: (@see https://bugs.eclipse.org/bugs/show_bug.cgi?id=38016)
        service.stop();
    }
```

(MariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/MariaDB4jService.java)
