### ISSUE TITLE
MacOS: Views are created in lower case

### ISSUE THREAD

**Issue by schoenknecht** [vorburger/MariaDB4j#366]
When working on a Mac OS system and when creating a view in an Embedded Maria DB the view name ist created in lower case even if the view name is written in Camel Case in the Create statement. 
This works for Table names, but not for View names.

**Comment by sluk3r** [comment]
I‘d like to analyze this issue, and if it reappear, I'd like to solve it

**Comment by sluk3r** [comment]
@schoenknecht would you like to give me some code, in order to analyze it.

**Comment by vorburger** [comment]
Hello! 

Thank you for your interest in this project. 

This issue has nothing to do per se with MariaDB4j; this project just "wraps" MariaDB itself. So you need to take this up with the database itself, not this Java wrapper. Hope this makes sense? I'll therefore be closing this issue. Please comment if you disagree and opine that this is an issue with this project (the MariaDB4j Java library).

M.
