### ISSUE TITLE
Add automatic-module name to manifests

### ISSUE THREAD

**Issue by jensli** [vorburger/MariaDB4j#372]
Add an entry for automatic module name to the JAR manifest files of the runtime libraries.

I get warnings when building my project because the the MariaDB4j module name is derived from the JAR name.

Such a manifest entry looks like this:

Automatic-Module-Name: ch.vorburger.mariadb4j

It can be generated with the Maven.

More information here:

http://branchandbound.net/blog/java/2017/12/automatic-module-name/

MariaDB4j-version: 2.6.2

**Comment by vorburger** [comment]
@jensli you are very welcome to contribute a pull request with what you need to this project!

**Comment by jensli** [comment]
> @jensli you are very welcome to contribute a pull request with what you need to this project!

I spent some time trying to figure out how to do this actually, but I didn't understand to which POM files I should add the configuration.

It is not possible for me to spend more time on it, sorry.

**Comment by vorburger** [comment]
Pending PR #387, pending a new minor ch.vorburger.exec version release.

**Comment by jensli** [comment]
Thanks for a nice tool Michael! I think this change will help it too stay relevant for post-9 Java versions.
