### ISSUE TITLE
If baseDir is set libedir has to be repointed too to make use of bundled native libs

### ISSUE THREAD

**Issue by anverus** [vorburger/MariaDB4j#39]
Linux native dependency includes two bundled libraries libjemalloc and libeaio.
If we change BaseLib from default these libraries would not be found and in order to fix that LibDir should be set relative to BaseLib. To reproduce - run it on linux with basedir set to something other then SystemUtils.JAVA_IO_TMPDIR + "/MariaDB4j/base"

```
            configBuilder = DBConfigurationBuilder.newBuilder();
            configBuilder.setBaseDir(dbFolder.getAbsolutePath());
            configBuilder.setLibDir(new File(dbFolder, "libs").getAbsolutePath());  // bundled libs are not found if LibDir is not set to this relative path
```

It is due to code in DBConfigurationBuilder constructor
```
        this.baseDir = SystemUtils.JAVA_IO_TMPDIR + "/MariaDB4j/base";
        this.libDir = this.baseDir + "/libs";

```
If you leave libDir as null on initialization and change implementation of getLibDir I would this it would do the trick

```
public String getLibDir() {
      if (this.libDir == null)
          return this.baseDir+"/libs"
      else  
         return this.libDir;
}
```

**Comment by vorburger** [comment]
Would you be willing to create a Pull Request with what you've outlined
above?

**Comment by anverus** [comment]
OK. It is about time I started using github correctly :) I'll create it
over the weekend. Thank you for great product :)

**Comment by vorburger** [comment]
@anverus thanks for this bug report and contribution https://github.com/vorburger/MariaDB4j/pull/40/ ! I've just merged it to master now (and a deploy of a new 2.2.1 including this to Maven Central should follow within the hour or so, hopefully).

Please note that in https://github.com/vorburger/MariaDB4j/commit/3ed30237c00784c485ed4ebe6af4802a826b3f3c in addition to the 3 new Unit Tests you've added in DBConfigurationBuilderTest (thank you!), I've also added additional non-regression integration testing for this problem in the MariaDB4jSampleOtherTest and MariaDB4jSpringServiceOverrideBySetTest.

I hope that it is OK that I've also added you to the https://github.com/vorburger/MariaDB4j/blob/master/CONTRIBUTORS.md file, according to https://github.com/vorburger/MariaDB4j/blob/master/CONTRIBUTING.md. You're also more than welcome to add yourself and/or Trip Advisor to the https://github.com/vorburger/MariaDB4j/blob/master/USERS.md via a new PR if you like.

**Comment by anverus** [comment]
Hi Michael,

Thank you for managing such a useful product :)

Just to share a bit more information on how we use it maybe for some
insights and to share some workarounds
We use it to run integration tests against embedded MariaDB. We run it in
MacOSX machines (developers) and Linux (Ubuntu / CentOS).
Running parallel tests require separate DB per test - so we create separate
instance of mysql deploying it to separate temp directory for each test
using setBaseLib / setDataLib.

One minor problem we had on Mac: if Firewall is enabled and MariaDB
instance started, MacOSX pops a dialog to a tune of - "Do you want to allow
incoming connections to mysqld? Allow / Deny". If left unanswered it
disappears after instance is terminated but considering that we run
multiple instances it pops up quite a few of them and it makes using
machine pretty hard as these popups grab cursor.
Workaround was to add

this.configBuilder.addArg("--bind-address=localhost");

I was not sure where to put that info and if it is going to be helpful to
others :)

Thank you again for your great work.
