### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib

### ISSUE THREAD

**Issue by ebleeker** [vorburger/MariaDB4j#411]
with the current openssl on my macos the file for dylib is

 /usr/local/opt/openssl/lib/libssl.1.1.dylib 

and on startup the mariadb4j is refering to 

/usr/local/opt/openssl/lib/libssl.1.0.0.dylib

is it possible to update the dependency for openssl@1.1 ?

**Comment by niom** [comment]
There's a problem with getting working binaries for OSX that has been tried to be fixed by multiple different people. 

There's a workaround for your problem at hand in this thread:
 https://github.com/vorburger/MariaDB4j/issues/288

**Comment by niom** [comment]
Apparently when upgrading OSX to Big Sur the workaround does not work anymore and it will be blocked by Cortex.

**Comment by galimru** [comment]
Creating these symlinks helped me on MacOS 11.2.3 (Big Sur).

```
ln -s /usr/lib/libcrypto.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
ln -s /usr/lib/libssl.dylib /usr/local/opt/openssl/lib/libssl.1.0.0.dylib 
```

You need to create these symlinks even you don't have target files `/usr/lib/libcrypto.dylib` and `/usr/lib/libssl.dylib`

**Comment by mournblade** [comment]
Hi, I'm trying to get MariaDB4J working on my new M1 MacBook Pro, and I'm not doing so great.

I've added symlinks like this and other threads have suggested, and while it now finds the ssl dylib files, I get another error message: 

"Reason: tried: '/usr/local/opt/openssl/lib/libssl.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))"

I am running the M1 version of both libssl and mariadb, both installed with Homebrew. 

Anyone knows how to get this working?

**Comment by vorburger** [comment]
M1 CPU architecture support is a separate problem from this issue; I've created new #497 specifically re. M1.

**Comment by vorburger** [comment]
Closing this because my understanding is that the"right way to properly fix this" is probably "just" needs someone who needs this to work to contribute a PR for #484, or #344 or #293.

**Comment by Zyh2333** [comment]
> Hi, I'm trying to get MariaDB4J working on my new M1 MacBook Pro, and I'm not doing so great.
> 
> I've added symlinks like this and other threads have suggested, and while it now finds the ssl dylib files, I get another error message:
> 
> "Reason: tried: '/usr/local/opt/openssl/lib/libssl.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))"
> 
> I am running the M1 version of both libssl and mariadb, both installed with Homebrew.
> 
> Anyone knows how to get this working?

I found the "libssl.1.0.0.dylib" and "libcrypto.1.0.0.dylib" in another app's /Contents/Resources/libs dir, and I copy these two files into /usr/local/opt/openssl/lib/ dir, then it works

**Comment by Zyh2333** [comment]
> > Hi, I'm trying to get MariaDB4J working on my new M1 MacBook Pro, and I'm not doing so great.
> > I've added symlinks like this and other threads have suggested, and while it now finds the ssl dylib files, I get another error message:
> > "Reason: tried: '/usr/local/opt/openssl/lib/libssl.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))"
> > I am running the M1 version of both libssl and mariadb, both installed with Homebrew.
> > Anyone knows how to get this working?
> 
> I found the "libssl.1.0.0.dylib" and "libcrypto.1.0.0.dylib" in another app's /Contents/Resources/libs dir, and I copy these two files into /usr/local/opt/openssl/lib/ dir, then it works

Maybe just need these two files in x86_64 architecture, you can download a openssl package with x86_64 architecture for a try

**Comment by tupolev** [comment]
Silly addition: cloning or linking /usr/local/opt/openssl/ from /usr/local/opt/openssl@1.0/ directory seems to make it work. I followed all steps and installed openssl 1.0 with lots of weird work but it insisted on loading from /usr/local/opt/openssl/ and links didn't work, so I dumped the whole folder. Now /usr/local/opt/openssl/ is a clone of /usr/local/opt/openssl@1.0/ and the test tool which uses mariadb runs successfully.

**Comment by abainer-quotient** [comment]
> Hi, I'm trying to get MariaDB4J working on my new M1 MacBook Pro, and I'm not doing so great.
> 
> I've added symlinks like this and other threads have suggested, and while it now finds the ssl dylib files, I get another error message:
> 
> "Reason: tried: '/usr/local/opt/openssl/lib/libssl.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))"
> 
> I am running the M1 version of both libssl and mariadb, both installed with Homebrew.
> 
> Anyone knows how to get this working?

following steps worked for me:

1. arch -x86_64 /usr/local/bin/brew install rbenv/tap/openssl@1.0
2. sudo mkdir -p /usr/local/opt/openssl/lib
3. sudo ln -s /usr/local/opt/openssl@1.0/lib/libssl.1.0.0.dylib /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
4. sudo ln -s /usr/local/opt/openssl@1.0/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib

**Comment by kangshilei** [comment]
> > 嗨，我正在尝试让 MariaDB4J 在我的新 M1 MacBook Pro 上运行，但我做得不是很好。
> > 我已经添加了这样的符号链接，并且其他线程已经建议了，虽然它现在找到了 ssl dylib 文件，但我收到了另一条错误消息：
> > “原因：尝试过：'/usr/local/opt/openssl/lib/libssl.1.0.0.dylib'（mach-o 文件，但架构不兼容（有'arm64'，需要'x86_64'））”
> > 我正在运行 libssl 和 mariadb 的 M1 版本，它们都与 Homebrew 一起安装。
> > 任何人都知道如何让这个工作？
> 
> 以下步骤对我有用：
> 
> 1. 拱 -x86_64 /usr/local/bin/brew install rbenv/tap/openssl@1.0
> 2. sudo mkdir -p /usr/local/opt/openssl/lib
> 3. sudo ln -s /usr/local/opt/openssl@1.0/lib/libssl.1.0.0.dylib /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
> 4. sudo ln -s /usr/local/opt/openssl@1.0/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib

i cant install openssl@1.0 and where can i find this code

**Comment by Shettyyy** [comment]
Following steps worked for me:
1. cd ~/Downloads
2. mkdir homebrew
3. curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
4. sudo mv homebrew /usr/local/homebrew
5. export PATH=$HOME/bin:/usr/local/bin:$PATH ( only if this is not already present in ~/.zshrc file )
6. curl https://raw.githubusercontent.com/rbenv/homebrew-tap/e472b7861b49cc082d1db0f66f265368da107589/Formula/openssl%401.0.rb -o openssl@1.0.rb
Edit this file -> 
add # sign to the line system "make", "test" (comment out)
replace 1.0.2u with 1.0.2t ( for my specific use case I wanted 1.0.2t or else you can skip this )
7. arch -x86_64 /usr/local/bin/brew install ./openssl@1.0.rb
8. rm -rf ./openssl@1.0.rb
9. sudo mkdir -p /usr/local/opt/openssl/lib
10. sudo ln -s /usr/local/homebrew/Cellar/openssl@1.0/1.0.2t/lib/libssl.1.0.0.dylib /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
11. sudo ln -s /usr/local/homebrew/Cellar/openssl@1.0/1.0.2t/lib/libcrypto.1.0.0.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
