### ISSUE TITLE
Using local mariadb install results in mariaDB4j.baseDir getting deleted

### ISSUE THREAD

**Issue by slangeberg** [vorburger/MariaDB4j#416]
While using MariaDB4j during SpringBoot integration tests, I am trying to avoid OpenSSL 1.0 errors on Mac as seen here:
https://github.com/vorburger/MariaDB4j/issues/288

I want to run using local mariadb which has correct openssl linkage. Following directions here:
https://github.com/vorburger/MariaDB4j#user-content-how-java

> If you would like to / need to start a specific DB version you already have, instead of the version currently packaged in the JAR, you can use DBConfigurationBuilder setUnpackingFromClasspath(false) & setBaseDir("/my/db/") or -DmariaDB4j.unpack=false -DmariaDB4j.baseDir=/home/you/stuff/myFavouritemMariadDBVersion.

In gradle project using : 

`    implementation "ch.vorburger.mariaDB4j:mariaDB4j:2.4.0"      `

And spring boot config:
```
mariaDB4j.baseDir=/usr/local/Cellar/mariadb@10.2/10.2.36
mariaDB4j.unpack=false
```
And run:
`./gradlew integrationTest`

Test is successful, but the plugin seems to delete contents of 'mariaDB4j.baseDir', so now my locally managed mariadb install is deleted, which is not expected behavior :)

And now i can see it right in the logs:
`2021-01-26 17:12:03.592-0600 | Shutdown Hook Deletion Thread for Temporary DB /var/folders/19/6k5m8tp95r32mx2316krrsh00000gq/T/MariaDB4j/data/57036 | INFO  | ch.vorburger.mariadb4j.DB | NO_USER | NO_SUBDOMAIN | cleanupOnExit() ShutdownHook quietly deleting temporary DB base directory: /usr/local/Cellar/mariadb@10.2/10.2.36`

I can see behavior in DB.java now - looks like bug at line 407 - 
```
                if (dataDir.exists() && (configuration.isDeletingTemporaryBaseAndDataDirsOnShutdown() && Util.isTemporaryDirectory(dataDir.getAbsolutePath()))) {
                    logger.info("cleanupOnExit() ShutdownHook quietly deleting temporary DB data directory: " + dataDir);
                    FileUtils.deleteQuietly(dataDir);
                }
                if (baseDir.exists() && (configuration.isDeletingTemporaryBaseAndDataDirsOnShutdown() && Util.isTemporaryDirectory(dataDir.getAbsolutePath()))) {
                    logger.info("cleanupOnExit() ShutdownHook quietly deleting temporary DB base directory: " + baseDir);
                    FileUtils.deleteQuietly(baseDir);
                }
```
As this line 
```
baseDir.exists() && (configuration.isDeletingTemporaryBaseAndDataDirsOnShutdown() && Util.isTemporaryDirectory(dataDir.getAbsolutePath()))
```
should probably be:
```
baseDir.exists() && (configuration.isDeletingTemporaryBaseAndDataDirsOnShutdown() && Util.isTemporaryDirectory(baseDir.getAbsolutePath()))
```

EG: only delete baseDir if baseDir is temp directory. NOT if dataDir is temp directory :)

**Comment by little-pan** [comment]
Is this "/usr/local/Cellar/mariadb@10.2/10.2.36" a temp directory? This default behavior of mariaDB4j is very dangerous and serious!!!

**Comment by slangeberg** [comment]
That is local Homebrew install of mariadb. Package manager for Mac OS. Should not be dangerous

**Comment by kcbaltz** [comment]
Did you ever get this working?  I'd also like to avoid the openssl issue and save the install time for re-installing MariaDB with every test

**Comment by vorburger** [comment]
A Pull Request proposing a solution for this would be welcome.

Wouldn't the simplest solution be simply not to delete if unpack is false, instead of the temporary directory approach?

**Comment by robin-xyzt-ai** [comment]
Note that the current version of the code no longer contains this wrong if check that is reported in the original issue.
According to this issue, the code used to be
```
if (baseDir.exists() && ... Util.isTemporaryDirectory(dataDir.getAbsolutePath()))
   -----------                                                                 ----------
```
while the current code correctly uses
```
if (baseDir.exists() && ... Util.isTemporaryDirectory(baseDir.getAbsolutePath()))
    -----------                                                               ----------
```

[link to code](https://github.com/vorburger/MariaDB4j/blob/c3ff55767b1d66741c8d39edc5ef1888ce0ee91e/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DBShutdownHook.java#L306)

I would think that means the issue can be closed

**Comment by vorburger** [comment]
> think that means the issue can be closed

@robin-xyzt-ai thank you! Let me close this, if anyone reading this still sees the problem **in latest v2.5.0** (see #334) please shout.
