### ISSUE TITLE
Fully automated remote release process

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#453]
https://jreleaser.org by @aalmiray looks neat.

Perhaps we could adopt it to fully automate future releases.

I probably won't have the spare cycles to do this myself in the near future, but I'm opening this issue for anyone who wants to help.

My first priority to revive on project (which I had to neglect due to other life priorities) is simply #334.

**Comment by aalmiray** [comment]
JReleaser can help automating GitHub releases as well as announcements.
Based on a quick glance at MariaDB4j I'd suggest the following configuration:

- releasing to GitHub (for obvious reasons ;-)
- upload the CLI uberjar as part of the release
- announcing to Twitter
- announcing/publishing the uberjar to Sdkman!

Other options may be considered depending how you'd like consumers to find and use the project.

**Comment by vorburger** [comment]
> - announcing to Twitter

Automatically? Neat!

> Other options may be considered depending how you'd like consumers to find and use the project.

@aalmiray MariaDB4j is primarily used as a regular Java library, from Maven central. There's nothing to "release" on GitHub, or Skdman (that I can think of; that CLI uberjar is a gimmick for illustration but I doubt it's much used by anyone).

When manually releasing, I normally use Maven deploy interactively, see doc in the README, and it creates a tag, with GPG signing, and whatever else that does.

So I guess what one would mostly want, in a project like this, is simply fully automate pushing to Maven central on... I'm not sure, probably a Git tag? (But how would this work VS the tag mvn deploy wants to create.) Or somehow manually trigger it?

I would also have to put a GPG key into a GitHub secret, presumably?

Is JReleaser actually a good fit for this?

**Comment by aalmiray** [comment]
FWIW I had a look at the current setup and it seems you have all the pieces in place to publish releases to Maven Central. Early in 2021 I wrote two blog posts on automating releases using GitHub Actions:

https://andresalmiray.com/publishing-to-maven-central-using-apache-maven/
https://andresalmiray.com/revisiting-publication-to-maven-central-with-apache-maven/

The instructions on the pom files are very similar to what MariaDB4J already has albeit at different places in the file structure).
