### ISSUE TITLE
New Windows MariaDB version 10.1.20, more recent than current 10.0.13 in order to support JSON type introduced in 10.0.16

### ISSUE THREAD

**Issue by ashot-karapetyan** [vorburger/MariaDB4j#49]
MariaDB supports JSON type starting with 10.0.16.
But I can't create JSON field here.
Do  you planning to support it ?

**Comment by vorburger** [comment]
@ashot-karapetyan thank you for your feedback and first MariaDB4j contribution (this issue).

There is nothing in this library, MariaDB4j, which is just a Java wrapper around a native version of mariadb, related to JSON, so I'm not sure what you mean by "I can't create JSON field here" - perhaps you would like to clarify?

It's possible that perhaps you are using MariaDB4j with an older version of MariaDB than 10.0.6.  [The latest MariaDB4j wraps more recent version of MariaDB than 10.0.6](https://github.com/vorburger/MariaDB4j/tree/master/DBs), so it should be OK. This [documentation explains how you contribute more recent version of the native binaries](https://github.com/vorburger/MariaDB4j#mariadb-database-jars-and-version-upgrades).

**Comment by vorburger** [comment]
@ashot-karapetyan https://github.com/vorburger/MariaDB4j/pull/56 from @clfsoft should fix this... 

I'll see to get https://github.com/vorburger/MariaDB4j/pull/56 released, and then plan to close this.

**Comment by vorburger** [comment]
The artefact ch.vorburger.mariaDB4j:mariaDB4j-db-win32:10.1.20 contributed in https://github.com/vorburger/MariaDB4j/pull/56/ was just released to Maven central. (As it's a big, 7.5 MB mariaDB4j-db-win32-10.1.20.jar, it may take several hours to fully propagate through their CDN.)

**Comment by vorburger** [comment]
https://github.com/vorburger/MariaDB4j/compare/db-win32-10.1.20 will switch the default dependency; perhaps you'd like to test this, @ashot-karapetyan or @clfsoft or @paulroemer or @lozanoco or @lpearson05, if you are on or have access to Windows (FYI I do not) ?

**Comment by vorburger** [comment]
MariaDB4j v2.2.3 has just been being released to Maven Central, and is in the process of CDN dist.

It has the dep. to db-win32-10.1.20 by default, which should solve this "out of the box".

Done.
