### ISSUE TITLE
needs happy path example

### ISSUE THREAD

**Issue by jottinger** [vorburger/MariaDB4j#50]
The docs show db.getConnection() as the correct way to get a connection (go figure) but that method is no longer part of the API; it would be nice to see an end-to-end example of a client project using mariadb4j so users don't have to work out the process every time they need to crank up mysql in a project.

**Comment by vorburger** [comment]
@jottinger thanks for the feedback.. [MariaDB4jSampleTutorialTest](https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java) shows how to use MariaDB4j.

Would you be willing to contribute a pull request with an update to the root README to clarify?

**Comment by jottinger** [comment]
Of course.

**Comment by vorburger** [comment]
Cool, thank you. I'll make sure to merge it promptly! - Perhaps say something in it that the DriverManager used in the MariaDB4jSampleTutorialTest is just an example - a real world app may use your favourite connection pool, etc.

**Comment by jottinger** [comment]
Well, my thought is that a simple "Look, here's using standard JDBC with
mariadb4j" would be enough, with more explanation focusing on the fqact
that ANYTHING - including connection pools - would leverage that same
process. Let me write it up, we can easily tune it to be more effective if
we need to.

On Mon, Oct 10, 2016 at 8:44 AM, Michael Vorburger <notifications@github.com

**Comment by vorburger** [comment]
Merged your https://github.com/vorburger/MariaDB4j/pull/51 (thank you!), amended with https://github.com/vorburger/MariaDB4j/commit/39ce8b1a7dd8e35e8ee1da3aa83bbe1a6f3957b7 - done!

**Comment by jottinger** [comment]
Ah, nice. I like it. Well done, thank you.
