### ISSUE TITLE
no place to specify the database character set  and database  collation 

### ISSUE THREAD

**Issue by clfsoft** [vorburger/MariaDB4j#52]
the default  should be utf8

collation_server=utf8_unicode_ci
character_set_server=utf8

**Comment by clfsoft** [comment]
use the command line args		
               config.addArg("--character-set-server=utf8");
		config.addArg("--collation-server=utf8_general_ci");

**Comment by vorburger** [comment]
@clfsoft thanks for your first contribution (in the form of this issue feedback) to MariaDB4j.

You may be able to work around this by using the addArg() method in the DBConfigurationBuilder, have you tried that?

Independent of whether DBConfigurationBuilder.addArg() works for above, I agree that it would probably be nice to have a configuration property for this. If you would be willing to contribute to the project by raising a pull request about this, I'd be happy to review and if OK merge it.

**Comment by vorburger** [comment]
@xf57212 while (finally) updating the [CHANGELOG](https://github.com/vorburger/MariaDB4j/blob/main/CHANGELOG.md) today, I remembered that #533 and #564 went into in v2.6.0, which fixed this!
