### ISSUE TITLE
Allow user to specify tmp directory for auto cleanup

### ISSUE THREAD

**Issue by xf57212** [vorburger/MariaDB4j#522]
I have a use case where I would like the base and data dirs deleted on shutdown, but do not want to store these directories within /tmp due to space constraints within that volume.

Currently java.io.tmpdir can be overwritten, but not without other potential consequences.

A better solution would be to allow the user to specify the directory they wish to use as a temporary directory, or default to the value of java.io.tmpdir if one is not provided.

**Comment by vorburger** [comment]
A Pull Request for this would be welcome.

Backwards compatibility for existing users must be kept in mind.

**Comment by vorburger** [comment]
@xf57212 while (finally) updating the [CHANGELOG](https://github.com/vorburger/MariaDB4j/blob/main/CHANGELOG.md) today, I remembered that #604 actually fixed this in v2.6.0!
