### ISSUE TITLE
log listener

### ISSUE THREAD

**Issue by dazi005** [vorburger/MariaDB4j#54]
How to listen binlog ?

**Comment by vorburger** [comment]
@dazi005 your question is a little bit short.. ;-) what exactly would you like to do?

The best is to look around the source code.. if you find that MariaDB4j is too "closed", and you cannot "get to" something you need, then you can just send a Pull Request to "open up" something you need.

For example, I suspect that you perhaps may be interested in writing your own org.apache.commons.exec.LogOutputStream implementation, to listen to logs? (I don't know what you mean by "binlog".)

Or you should then be able to add your implementation of OutputStream to the https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/src/main/java/ch/vorburger/exec/MultiOutputStream.java via its addOutputStream() ?

May this https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/src/main/java/ch/vorburger/exec/ManagedProcessBuilder.java#L190 helpful?

Best of luck. I'll close this issue in 1 month if there is no follow-up.

**Comment by vorburger** [comment]
Closing issue as timed out.
