### ISSUE TITLE
The problem for data

### ISSUE THREAD

**Issue by dazi005** [vorburger/MariaDB4j#55]
I stoped the service , then data miss ? How?  success?

**Comment by vorburger** [comment]
@dazi005 your question is a little bit short.. ;-) what exactly would you like to do?

I suspect that you probably are surprised that the DB is cleaned up after shutdown? That happens in https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/src/main/java/ch/vorburger/mariadb4j/DB.java#L347, IFF the data and/or base directory are in a temporary directory.

If you simply e.g. setDataDir() on the `DBConfigurationBuilder` when you initialize MariaDB4j to a directory that is not a temporary directory, then it will not get cleaned up on shutdown. Does that answer your question?

Best of luck. I'll close this issue in 1 month if there is no follow-up.

**Comment by vorburger** [comment]
Closing issue as timed out.

**Comment by vorburger** [comment]
PS: see also discussion in https://github.com/vorburger/MariaDB4j/issues/36
