### ISSUE TITLE
Support using locally installed MariaDB

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#560]
It occured to me that, before delving into #296 (containers), it could be neat, and maybe (?) fairly easy, to add support for launching "locally installed" MariaDB (or MySQL) binaries.

So then instead of depending on the `ch.vorburger.mariaDB4j:ch.vorburger.mariaDB4j` Maven artifact with its `mariaDB4j-db-linux64` / `mariaDB4j-db-win32` / `mariaDB4j-db-mac64` _"native database embedded in a JAR that is unpacked at run-time",_ one would `sudo dnf install mariadb-server` (or `apt install`  ..., or `brew install mariadb --build-from-source` from #497, or anything like that) and then use (only) the `mariaDB4j-core` module Maven artifact (which does not depend on those `-db-*`) to start a DB with binaries from `/usr/sbin/mariadbd` (or something like that).

Would reading this find this useful? Anyone willing to look into contributing it? Or be willing to test it?

**Comment by vorburger** [comment]
I had a brief first look at this, and at least one of the problems is that at least for me on Fedora, the `mysql_install_db` is in `/usr/bin/` but the `mysqld` is in `/usr/sbin` (note `bin` vs. **`s`**`bin`) - but MariaDB4j's `baseDir` assumes they are both in the same directory. So that needs a little bit of work.

**Comment by vorburger** [comment]
#565 implements this now. It's also a great illustration of why I'm still slightly torn whether this is a good idea at all... that PR as-is right now    still fails to build on TravisCI, because apparently the `mysql_install_db` that is installed on _Ubuntu 16.04.7 LTS_ has `[ERROR] unknown option '--no-defaults'` - and that shows that letting users of this library launch any MariaDB (or MySQL) version that's locally installed, as opposed to a fixed "embedded" version, can lead to more "variability" and less "reproducibility".

**Comment by vorburger** [comment]
The above is because I'm currently [running Travis](https://github.com/vorburger/MariaDB4j/blob/master/.travis.yml) without a `dist:` which apparently defaults to Ubuntu `xenial` 16.04 which [has ancient MySQL 5.7.30](https://docs.travis-ci.com/user/reference/xenial/#databases-and-services). I'm trying to switch it to running Travis on Ubuntu `focal` 20.04, which [has MySQL 8.0.21](https://docs.travis-ci.com/user/reference/focal/#databases-and-services) (and Java 11 instead of 8) in #566, which will likely solve the problem above.

PS: Anyone reading this and using MariaDB4j, please [Sponsor my maintenance this project](https://github.com/sponsors/vorburger)! I would very much appreciate it.

**Comment by vorburger** [comment]
MySQL 8.0.21 doesn't have `mysql_install_db` at all anymore, so the new test in #565 fails on Travis CI due to `Caused by: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "/usr/scripts/mysql_install_db" (in directory "/usr"): error=2, No such file or directory)`.

Supporting MySQL 8.x in addition to MariaDB wasn't really the goal of this issue, so I'll just use MariaDB instead of MySQL on Travis.

**Comment by vorburger** [comment]
#565 is now merged.

Perhaps it's worth documenting it on the [README](https://github.com/vorburger/MariaDB4j/blob/master/README.md) and not just in `testLocalMariaDB()` of [`MariaDB4jSampleTutorialTest`](https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j/src/test/java/ch/vorburger/mariadb4j/tests/MariaDB4jSampleTutorialTest.java)?

Does anyone reading this want to make a documentation contribution for this? It's basically just (something like) this:

```java
DBConfigurationBuilder config = DBConfigurationBuilder.newBuilder();
config.setPort(0); // 0 => autom. detect free port
config.setUnpackingFromClasspath(false);
config.setLibDir(SystemUtils.JAVA_IO_TMPDIR + "/MariaDB4j/no-libs");
config.setBaseDir("/usr");
config.setExecutable(Server, "/usr/sbin/mysqld");
```

Or perhaps this could be further simplified... but I'm not entirely sure yet how/why/where, because e.g. the `setExecutable()` is OS/distro dependant, e.g. for Mac M1 support for #497, that would have to be tweaked to wherever `brew install mariadb --build-from-source` puts `mysqld` (and possibly other MariaDB executables). Feedback welcome.

_PS: Anyone reading this and using MariaDB4j, please [Sponsor my maintenance this project](https://github.com/sponsors/vorburger)! I would very much appreciate it._

**Comment by stevenodb** [comment]
This solution works. A downside on a big project is that we need to alter our tests, but the config above is not going to be the same for every developer computer (mixed Linux/macOS environment). Is something like environment variable a solution worth considering/investigating, you believe?

**Comment by vorburger** [comment]
@stevenodb something built-in based on environnement variable/s could be neat, if you want to make a PR for this. (But M1 binaries contrib in #497 would "add even more value" to this project, IMHO.)

**Comment by cleverpig** [comment]
the simplest way:
create a script startup mysql at first and then start my app.

**Comment by mrdziuban** [comment]
@vorburger this is fantastic and has allowed me to get MariaDB4j working on my M1 Mac! Is there any chance you could release a new version or a snapshot with these changes? I'd be happy to help if there's any way I can

**Comment by vorburger** [comment]
@mrdziuban good point, watch #621.

**Comment by vorburger** [comment]
@mrdziuban would you consider raising a PR to contrib doc about this to the README? See above.

**Comment by mrdziuban** [comment]
Sure thing @vorburger, see #622

**Comment by vorburger** [comment]
https://github.com/vorburger/MariaDB4j#how-using-existing-native-mariadb-binaries
