### ISSUE TITLE
Disable logs or just print error logs

### ISSUE THREAD

**Issue by 3l0w** [vorburger/MariaDB4j#571]
Hello, thanks for this amazing library.
Is there is a way to limit the logs and just keep errors logs, just disable all logs coming from this library.

**Comment by vorburger** [comment]
You "just" have to configure the logging backend you use accordingly. MariaDB4j just uses the SLF4j Logging API. So you have to check the documentation of Logback or Log4j2 or JUL, depending on which one your application uses, to see how to silence INFO level logging.

**Comment by 3l0w** [comment]
Okay i think i understand thanks
