### ISSUE TITLE
Spring-boot integration context loading for every test case

### ISSUE THREAD

**Issue by jamalmatgmail** [vorburger/MariaDB4j#583]
Hi,
I have recently migrated from H2 to MariaDB4J. Test cases are executing but it is taking longer time than H2. When I see the logs, the spring context is loaded for every test case and the database schema initialisation is happening. We have hibernate.hbm2ddl = auto setting to sync the database schema.

Any help would be appreciated. Basically, I want only to load the DB only once and use it for all the test cases.

**Comment by vorburger** [comment]
Hello! 

Thank you for your interest in this project. 

The problem you are raising here isn't particular specific to MariaDB4j, but perhaps more of a general how to use Spring Framework question.

I'm unfortunately unable to offer you support for this particular problem, but have full faith in you that you will be able to figure this out yourself by searching more online.

I'll therefore be closing this issue. Please comment if you disagree and opine that this is an issue with this project (the MariaDB4j Java library).

M.
