### ISSUE TITLE
Support parallel execution

### ISSUE THREAD

**Issue by simonzkl** [vorburger/MariaDB4j#602]
So I've been testing MariaDB4j with parallel unit test execution and discovered that in its current form, it does not work. The main issue is that MariaDB instances share the same system-wide `/tmp` directory for temporary tables, and the name of these files often clash between instances, leading to errors like this:
```
Message    : Can't find file: '/tmp/#sql16803_8_ef.MAI' (errno: 2 "No such file or directory")
```

Most often these error occur when running database migrations or when setting up system tables with `mysql_install_db`. The issues with migrations can be worked around by configuring mysqld do run with its own tmpdir (e.g. `--tmpdir=/tmp/m4j-<random token>`. However with the current API, we cannot set the tmpdir for `mysql_install_db`. I've patched this in my code by writing a wrapper around `mariadb4j.DB` and overriding `createDBInstallProcess`. That seems to have solved the issue for me and now tests can execute in parallel without any issues.

My suggestion for mariadb4j would be to configure tmpdir isolation by default for both `mysqld` and `mysql_install_db`. We could probably namespace the data dir and sockets in the same base directory. I can prepare a PR for this, just wanted to confirm if you agree with this approach.

**Comment by vorburger** [comment]
That sounds like a great idea and plan - PR for this most welcome!

**Comment by vorburger** [comment]
@simonzkl with #604 (just now) merged, can we close this issue, or did you want to make further contributions for this?

**Comment by simonzkl** [comment]
Nope, that tmpdir isolation was all that was needed here. I think it's fine to close this. Thanks!
