### ISSUE TITLE
When I run Unit Tests using Mac wtih this, I get a Row size too large error when creating the schema in which the unit tests are run against

### ISSUE THREAD

**Issue by rkumar0322** [vorburger/MariaDB4j#605]
When I run Unit Tests using Mac wtih this, I get a Row size too large error when creating the schema in which the unit tests are run against. But When I use Windows, it does not have the same issue

**Comment by vorburger** [comment]
@rkumar0322 Thank you for your interest in this project. Without further details, such as what error you actually faced, this issue unfortunately isn't actionable as-is. I'm therefore closing it; thanks for understanding.
