### ISSUE TITLE
Error - Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by vikrampatankar** [vorburger/MariaDB4j#61]
Hi,

When trying to execute this - 
`Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/myDb", "root", "");`

I'm getting error - 

> Access denied for user 'root'@'localhost' (using password: NO)

Here is my full code 

```
static class MySqlRule extends ExternalResource {
        DB db = null;

        MySqlRule() {
            DBConfigurationBuilder configBuilder = DBConfigurationBuilder.newBuilder();
            configBuilder.setPort(3306); // OR, default: setPort(0); => autom. detect free port
            try {
                db = DB.newEmbeddedDB(configBuilder.build());
                db.start();
                db.source("db/1_create-database.sql");
                db.source("db/2_create-tables.sql", "root", "", "myDb");
                db.source("db/3_seed-data.sql", "root", "", "myDb");
            } catch (ManagedProcessException e) {
                e.printStackTrace();
            }
        }

        @Override
        protected void after() {
            try {
                db.stop();
            } catch (ManagedProcessException e) {
                e.printStackTrace();
            }
        }
    }
```

**Comment by Maldivia** [comment]
`DriverManager.getConnection("jdbc:mysql://localhost/myDb", "root", "");`
This will try to connect on port 3306. You probably have another mysql or mariaDB running on the system on port 3306, which it then tries to connect to.


Try using `DriverManager.getConnection(configBuilder.getURL("myDb"), "root", "")`

Or specify a different port, and remember to update the connection URL accordingly, for instance: `configBuilder.setPort(33306);`
`DriverManager.getConnection("jdbc:mysql://localhost:33306/myDb", "root", "");`

**Comment by vorburger** [comment]
@vikrampatankar can we close this then? (Without hearing back from you within 1 week, I'll close it.)

@Maldivia thanks for answering this!

**Comment by bjornblomqvist** [comment]
I think its time to close this.

**Comment by vorburger** [comment]
Closing as "Answered".
