### ISSUE TITLE
Support for jakarta annotation

### ISSUE THREAD

**Issue by gaetannandelec-ibboost** [vorburger/MariaDB4j#648]
MariaDB4jService relies on javax.annotation.PostConstruct to start itself in a Spring environment. 

With Spring 6 out and the migration to jakarta annotations, this is not working anymore

**Comment by vorburger** [comment]
Salut, merci for this feedback; good to know. If this is important to you, please raise a Pull Request to contribute to this open source by fixing this problem. (I'm happy to help you learn how to do this, if required.)

**Comment by gaetannandelec-ibboost** [comment]
Sure, i am happy to contribute! i will take a look in the coming days. Thank you

**Comment by gaetannandelec-ibboost** [comment]
#669

**Comment by vorburger** [comment]
@gaetannandelec-ibboost how is that PR coming along? 😸 

FYI I've now fixed the (previously broken) build, so now is a great time to contrib a PR... 😄

**Comment by GaetanNandelec** [comment]
Hello, sorry for the delay on this! i made the change on my personal github account but it overlapses #650 so i am not sure what is the best approach? 
I am also getting a failed unit test : `defaultExecutables(ch.vorburger.mariadb4j.tests.DBConfigurationBuilderTest)`
I am trying to figure out

**Comment by vorburger** [comment]
> it overlapses #650 so i am not sure what is the best approach? 

Small separate PRs are usually, if it's possible.

Or just wait for #650 to be resolved? I have a WIP Draft PR, something still NOK; I'll try to wrap that up perhaps next weekend.

> I am also getting a failed unit test : `defaultExecutables(ch.vorburger.mariadb4j.tests.DBConfigurationBuilderTest)`

You could open a separate new issue about that, with more details?

Or if you suspect it's a local issue for you, it's not unheard of 🙂 to just go ahead and raise a (still Draft?) PR, for you to see if it would pass the CI on the project (I don't mind if you want to try that).

**Comment by GaetanNandelec** [comment]
it's probably local, i need to look into it a bit more. Yes as part of the changes, i kind of went through #650 as well and made changes. I will isolate this to this ticket and make a small PR to start with. Thanks for your patience!

**Comment by GaetanNandelec** [comment]
Added pull request for your review https://github.com/vorburger/MariaDB4j/pull/693 .
Unit tests are not working in windows but there is already a ticket for that. I was able to run them under linux so all good
