### ISSUE TITLE
Java 17 instead of Java 11 (i.e. build with - and therefore effectively require)

### ISSUE THREAD

**Issue by vorburger** [vorburger/MariaDB4j#650]
Does anyone reading this have any thoughts, both Pro as well as Con, about switching this project from Java 11 to Java 17?

Recent contributors (@jejanim @chrisbloe @MazenAmria @mrdziuban @simonzkl @dassio @skyding1212  @rkumar0322 @simonzkl @bib-marko @ StruckCroissant @jamalmatgmail @gaetannandelec-ibboost @3l0w @Blanco27) any input? Do you MIND if this project were to require Java 17 instead of Java 11 in a next (future) release like 2.7.0 or 3.0.0 or whatever version number I chose for it?

This question has come up in #638.

**Comment by vorburger** [comment]
Full disclosure: I personally actually don't really care either way. I just want to avoid loosing end-users, because of this... 🤣

**Comment by 3l0w** [comment]
That don't bother me, we moved our code base recently to java 17

**Comment by gaetannandelec-ibboost** [comment]
Same here, i think it would be good given main project like Spring boot 3.0 / Hibernate 6 have moved to it

**Comment by MazenAmria** [comment]
We're considering upgrading to java 17 in the project which I'm using MariaDB4j in, so I'm fine with it.

**Comment by vorburger** [comment]
OK, then let's do this - I'm switching 2.6.1 (unreleased) to 3.0.0 in #690 and will then build with Java 17 instead of 11 (perhaps not today anymore, but on another upcoming weekend or so).

**Comment by vorburger** [comment]
Resolving now, as #691 just switched the build from Java 11 to 17 (on CI, for unreleased 3.0.0, watch #696).

**Comment by vorburger** [comment]
FTR: #1144 now documents this more explictly on the README.
