### ISSUE TITLE
NoSuchMethodError: org.apache.commons.io.FileUtils.deleteQuietly during  Shutdown Hook Deletion Thread for Temporary DB

### ISSUE THREAD

**Issue by petroskidragan** [vorburger/MariaDB4j#73]
I have problem with MariaDB4j . When I run it as Junit test , I get this error : 

Exception in thread "Shutdown Hook Deletion Thread for Temporary DB C:\Users\petroski\AppData\Local\Temp\MariaDB4j\data\53163" java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.deleteQuietly(Ljava/io/File;)Z
	at ch.vorburger.mariadb4j.DB$1.run(DB.java:369)

Any help with this issue ? 
Thank you

**Comment by vorburger** [comment]
@petroskidragan this means that the version of org.apache.commons.io.FileUtils which you have on the classpath of your application does not match [the 2.5 one in MariaDB4j's pom.xml](https://github.com/vorburger/MariaDB4j/blob/master/mariaDB4j-core/pom.xml#L37)... as 2.5 is the latest, you probably have a very old commons-io on your classpath which did not yet have [FileUtils' deleteQuietly, introduced in 1.4](https://commons.apache.org/proper/commons-io/javadocs/api-release/org/apache/commons/io/FileUtils.html#deleteQuietly(java.io.File)) ? 

To solve this issue for you, you should upgrade your version of Apache commons-io in your app.

Could you confirm that this issue can be closed? If I don't hear back from you within 1 month, I'll close it.

**Comment by petroskidragan** [comment]
Thank you so much for the help . It is OK now .

**Comment by vorburger** [comment]
[Standard Footer] PS: Shameless plug, consider https://www.patreon.com/vorburger to support MariaDB4j.
