### ISSUE TITLE
REQ: support alpine linux

### ISSUE THREAD

**Issue by gzm55** [vorburger/MariaDB4j#74]
Hi, when running MariaDB4j on a alpine container, we met error:

> ./mysqld: /usr/lib/libstdc++.so.6: no version information available (required by ./mysqld)

If we must depend gnu libstdc++, could we build a alpine version (based on musl libc) mysqld?

**Comment by vorburger** [comment]
@gzm55 from what I understand, this is more of request for the core MariaDB binaries than the MariaDB4j Java wrapper (this project) - would you agree? But if you would to make a contribution to core MariaDB which works on [Alpine Linux](https://alpinelinux.org) and then makea  JAR of that for use with MariaDB4j, I'm all for it... ;-) Contributions welcome - I'd certainly look at and merge anything like this. (But I myself wouldn't have the time to do this for you).

**Comment by gzm55** [comment]
OK, you are right. MariaDB has alpine version: https://pkgs.alpinelinux.org/package/edge/main/x86_64/mariadb

**Comment by vorburger** [comment]
@gzm55 OK, then I think what we're really saying here is that you would like to [contribute new binaries packaging](https://github.com/vorburger/MariaDB4j/#mariadb-database-jars-and-version-upgrades) (in the DB/ directory; like a mariaDB4j-db-alpine64-10.1.24-r0) to MariaDB4j?

Or, alternatively, why don't you just pre-install that Alpine MariaDB native package into your container? If you wanted to, you could still use MariaDB4j just to start and stop isolated fresh DBs from your Java tests code... this isn't how most typically use this library today - but you absolutely could, probably with a little bit of tweaks - I'd love contributions on that front, see https://github.com/vorburger/MariaDB4j/issues/59.

**Comment by gzm55** [comment]
@vorburger 

solution A: add binary in DB/, will result more predictable action on the machine, so most cases we prefer this one. but it is difficult to distinguish between linux and alpine at run-time when generate binary path.

solution B: described in #59 , could be very convenient in developing phase.

solution C: such as #59, maybe we can further fallback to local tcp port mode, which can be useful when the docker connecting the service from other container.

**Comment by vorburger** [comment]
@BenDave to carry over from your issue #80, how about you just install the MariaDB binary Alpine package which @gzm55 mentioned above in your container, and then use the MariaDB4j API mentioned in #59 (which FYI @gzm55 actually already works...) to control it - would that work for you?

[Standard Footer] PS: Shameless plug, consider https://www.patreon.com/vorburger to support MariaDB4j.
