### ISSUE TITLE
Start method need lot of time do execute 

### ISSUE THREAD

**Issue by petroskidragan** [vorburger/MariaDB4j#77]
Here is how I implemented MaridaDB4j : 
DBConfigurationBuilder configBuilder = DBConfigurationBuilder.newBuilder();
    configBuilder.setPort(0);
    this.db = DB.newEmbeddedDB(configBuilder.build());

    db.start();  //take a lot of time to start and make my unit test slow 
    String dbName = "object_registry";
    db.createDB(dbName);

So my problem is with db.start();  . It makes my unit test much slower than expected.
Any help with that , 
Thank you

**Comment by vorburger** [comment]
How long is "a lot of time" ? Seconds? Minutes? An hour?

MariaDB4j is for integration tests, not unit tests. It's normal that it will take "some time" to start up the native DB - it's an external process.

I'll close this issue as Answered if we don't hear back from you within 1 month.

**Comment by vorburger** [comment]
[Standard Footer] PS: Shameless plug, consider https://www.patreon.com/vorburger to support MariaDB4j.
