### ISSUE TITLE
Issues Running MariaDb4j on Docker Alpine

### ISSUE THREAD

**Issue by BenDave** [vorburger/MariaDB4j#80]
Hi,

I am encountering an issue when running MariaDb4j on a docker container based on Alpine. 

When starting up, MariaDb shows the following error message: ` error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`. 

The java library path that specifies the location for the shared libraries does contain `/usr/lib`, which is where libstdc++ is located, so the library should be loaded.

The issue does not seem related to the Alpine image itself as I am able to load that library specifically from a test using the following code: `System.load("/usr/lib/libstdc++.so.6")`

If in that test I replace that line of code with code to start the embedded MariaDb server,  the error is shown. To summarize, I can load libstdc++ programmatically but when it is loaded as part of MariaDb4j, this library can not be found.

I am also able to successfully start the MariaDb server from the host from which the docker container is running with MariaDb.

I am wondering if anybody has any insight to share on this. 

Attached is an extract of the failure.
[mariadb-failure.txt](https://github.com/vorburger/MariaDB4j/files/1142545/mariadb-failure.txt)

Many thanks ...

**Comment by vorburger** [comment]
@BenDave did you see there is a previous issue #74 which, I think, is about the same - if you agree, perhaps you'd like to close this issue, and we can continue the conversation there?

[Standard Footer] PS: Shameless plug, consider https://www.patreon.com/vorburger to support MariaDB4j.

**Comment by vorburger** [comment]
Closing this old issue as a duplicate.
