### ISSUE TITLE
How to change db config.

### ISSUE THREAD

**Issue by zmzmdr** [vorburger/MariaDB4j#91]
[background]
Some error i faced
" The total blob data length (10066357) is greater than 10% of the total redo log size (100663296). Please increase total redo log size."

-----------------
So i need change the db config param. like 'innodb_log_file_size'
Pls help me.

**Comment by vorburger** [comment]
@zmzmdr or anyone else watching this project willing to help:

I'm not sure how / where to change a parameter like `innodb_log_file_size` .. is this something that you could just do in your code via JDBC with a Statement for `SET GLOBAL innodb_fast_shutdown = 1` as per [this documentation](https://dev.mysql.com/doc/refman/5.6/en/innodb-data-log-reconfiguration.html)?

Or are you suggesting that MariaDB4j should have an API to set this, to change the `my.cnf` file? If you think that is useful, then a Pull Request contributing that could interesting.

**Comment by thesquaregroot** [comment]
[The MariaDB documentation](https://mariadb.com/kb/en/library/xtradbinnodb-server-system-variables/#innodb_log_file_size) suggests that you should be able to set this via command-line argument.

So adding that argument to the DBConfigurationBuilder should work:

`config.addArg("--innodb-log-file-size=#");`

**Comment by vorburger** [comment]
@thesquaregroot Thank You for contributing to this project [not just with a PR](https://github.com/vorburger/MariaDB4j/pull/133) but by helping here as well!

@zmzmdr I'll close this issue based on above. Please commentif NOK for you and we'll re-open.
