### ISSUE TITLE
Add option to not destroy built directories on JVM shutdown

### ISSUE THREAD

**Issue by svenerxleben** [vorburger/MariaDB4j#94]
Hi,   
It would be nice, if the created directories in the temp directory are not getting destroyed on JVM shutdown, to speed up the creation on further creations. We could let the OS handle the destruction process (since it is in the tmp directory). While developing this was somewhat annoying to always wait for rebuilding the database if some tests didn't succeed.  
I have in my local codebase a fix therefore, but it seems like I can't push the changes. If you're interested to add this feature, I could provide my small fix. This would prevent the destruction of the created directories and check on startup if they exist, but it only works if you set a fixed port. This would also add a new overloaded method for the DB class (method `public static DB newEmbeddedDB(DBConfiguration config, boolean destroyOnShutDown) throws ManagedProcessException`) which adds a new boolean where you can set if you want the destruction or not.  
All changes would be in the DB class.

**Comment by vorburger** [comment]
@svenerxleben thanks for taking the time to open this issue - appreciate your contribution to MariaDB4j.

You proably saw it only does the clean up if it's in `tmp`? If you do `setDataDir()` to something else it won't.

In https://github.com/vorburger/MariaDB4j/pull/84 for https://github.com/vorburger/MariaDB4j/issues/36 we (@paulroemer) added a new `setDeletingTemporaryBaseAndDataDirsOnShutdown()`, did you see that? Does that not work for you? Or I just need to release it? :smile:
