### ISSUE TITLE
GitHub 100 MB file limit prevents contributing latest MariaDB 10.2.11 linux x64

### ISSUE THREAD

**Issue by lde-avaleo** [vorburger/MariaDB4j#99]
Hi,

I was trying to port MariaDB 10.2.11 for win32 and linux x64. I 've followed guides and succeeded with win32. However it seems that mysqld file for linux x64 is bigger than 100MB which is github limit for single repository file.

Have you got any idea how to deal with that? Maybe we could replace DB's content to some zip files that would be unpacked and attached during maven build?

best regards,
lde

**Comment by vorburger** [comment]
@lde-avaleo could you point me to where I can download a MariaDB for Linux x64 where the mysqld file is bigger than 100 MB? I've just had a look at the old ones in this repo: both 10.1.13 and 10.1.23 were about 95 MB.. I admit I actually had never even [realized that GitHub had this limit](https://help.github.com/articles/what-is-my-disk-quota/), and [that you hit this error](https://help.github.com/articles/conditions-for-large-files/)... hm.

Apparently [Git Large File Storage](https://help.github.com/articles/versioning-large-files/) could help with this... but I haven't really completely understood yet how that works. If you are willing to explore that and tell me what you want me to do, then I'm all for it! :smiley: Have you tried [installing the Git LFS client](https://git-lfs.github.com), and see if with that you can push to your repo and then raise a PR? Will I have to do anything in particular? There is nothing to "enable" in Settings that I can see. Will people who do not have the LFS client installed still be able to clone to contribute? If not, I wonder if this may be the time to finally split the MariaDB4j core Java code from the DBs into a completely separate new Git repo...

@jai-deep I think this discussion will interest you as well?

**Comment by jai-deep** [comment]
@lde-avaleo  I actually tried a solution similar to your proposal some time back. I added a zip file to the repo and tried to unzip at the time of unpacking of the db. But I somehow got stuck when I got an error similar to this : https://github.com/vorburger/MariaDB4j/issues/42 . I didn't get time to work on this last week , will try this out again. You should try this out too, may be the way you implement this do the trick for us.

**Comment by jai-deep** [comment]
@vorburger I explored git-lfs, basically it changes large file in your repo with the pointer to that file that will be on git-lfs server. So its works perfectly fine for a person who has git-lfs client installed. But if he do not have it , his build will fail as he only got pointer files in his repo instead of the original files. To handle this we can have a instruction file in the repo , so that a person new to the project can build this. But yes, it will add little overhead for him.

**Comment by lde-avaleo** [comment]
@vorburger Well, personally I like keeping things simple and not to put too much on devs so I've skipped git-lfs try and followed zip file idea. 
@jai-deep I also had some issues while preparing linux package however the clue was to prepare zip file for win32 on Windows and linux on Linux (I used docker centos image from dockerhub). After all it worked for me. I'm going to issue a pull request where you can review my changes.

Thanks for your help!

**Comment by lde-avaleo** [comment]
I created pull request: https://github.com/vorburger/MariaDB4j/pull/100

best regards,
lde

**Comment by vorburger** [comment]
@lde-avaleo as we're about to merge your #100, OK for you if we close this issue now?

@jai-deep hope with you if, for now, we don't go the git-lfs route?

**Comment by lde-avaleo** [comment]
Solved in https://github.com/vorburger/MariaDB4j/pull/100
